/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "system_bluetooth.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_main_exports.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL callback 'openAdapterSuccess' ******/
static const FeatureType system_bluetooth_openAdapterSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_openAdapterSuccess_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_openAdapterSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'openAdapterFail' ******/
static const FeatureType system_bluetooth_openAdapterFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_openAdapterFail_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_openAdapterFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'openAdapterComplete' ******/
static const FeatureType system_bluetooth_openAdapterComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_openAdapterComplete_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_openAdapterComplete_parameters,
    .return_type = FT_VOID
};


static OptionalType system_bluetooth_OpenAdapterParams_member_operateAdapter_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_BOOLEAN,
    .ival = false
};

/****** for JIDL struct 'OpenAdapterParams' ******/
static ObjectMember system_bluetooth_OpenAdapterParams_struct_members[] = {
    { "operateAdapter", FT_MK_OPTIONAL(&system_bluetooth_OpenAdapterParams_member_operateAdapter_opt_type), offsetof(system_bluetooth_OpenAdapterParams, operateAdapter), sizeof(FtBool) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_openAdapterSuccess_callback_type), offsetof(system_bluetooth_OpenAdapterParams, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_openAdapterFail_callback_type), offsetof(system_bluetooth_OpenAdapterParams, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_openAdapterComplete_callback_type), offsetof(system_bluetooth_OpenAdapterParams, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_OpenAdapterParams_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_OpenAdapterParams) },
    .members = system_bluetooth_OpenAdapterParams_struct_members
};

system_bluetooth_OpenAdapterParams* system_bluetoothMallocOpenAdapterParams () {
    return (system_bluetooth_OpenAdapterParams*)FeatureMalloc(
        sizeof(system_bluetooth_OpenAdapterParams), FT_MK_COMPLEX_REF(&system_bluetooth_OpenAdapterParams_struct_type));
}


/****** for JIDL function 'openAdapter' ******/
static const FeatureType system_bluetooth_openAdapter_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_OpenAdapterParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_openAdapter_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_wrap_openAdapter) },
    .parameters = system_bluetooth_openAdapter_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'closeAdapterSuccess' ******/
static const FeatureType system_bluetooth_closeAdapterSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_closeAdapterSuccess_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_closeAdapterSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'closeAdapterFail' ******/
static const FeatureType system_bluetooth_closeAdapterFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_closeAdapterFail_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_closeAdapterFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'closeAdapterComplete' ******/
static const FeatureType system_bluetooth_closeAdapterComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_closeAdapterComplete_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_closeAdapterComplete_parameters,
    .return_type = FT_VOID
};


static OptionalType system_bluetooth_CloseAdapterParams_member_operateAdapter_opt_type = {
    .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
    .type = FT_BOOLEAN,
    .ival = false
};

/****** for JIDL struct 'CloseAdapterParams' ******/
static ObjectMember system_bluetooth_CloseAdapterParams_struct_members[] = {
    { "operateAdapter", FT_MK_OPTIONAL(&system_bluetooth_CloseAdapterParams_member_operateAdapter_opt_type), offsetof(system_bluetooth_CloseAdapterParams, operateAdapter), sizeof(FtBool) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_closeAdapterSuccess_callback_type), offsetof(system_bluetooth_CloseAdapterParams, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_closeAdapterFail_callback_type), offsetof(system_bluetooth_CloseAdapterParams, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_closeAdapterComplete_callback_type), offsetof(system_bluetooth_CloseAdapterParams, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_CloseAdapterParams_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_CloseAdapterParams) },
    .members = system_bluetooth_CloseAdapterParams_struct_members
};

system_bluetooth_CloseAdapterParams* system_bluetoothMallocCloseAdapterParams () {
    return (system_bluetooth_CloseAdapterParams*)FeatureMalloc(
        sizeof(system_bluetooth_CloseAdapterParams), FT_MK_COMPLEX_REF(&system_bluetooth_CloseAdapterParams_struct_type));
}


/****** for JIDL function 'closeAdapter' ******/
static const FeatureType system_bluetooth_closeAdapter_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_CloseAdapterParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_closeAdapter_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_wrap_closeAdapter) },
    .parameters = system_bluetooth_closeAdapter_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'GetAdapterSuccessResult' ******/
static ObjectMember system_bluetooth_GetAdapterSuccessResult_struct_members[] = {
    { "available", FT_BOOLEAN, offsetof(system_bluetooth_GetAdapterSuccessResult, available), sizeof(FtBool) },
    { "discovering", FT_BOOLEAN, offsetof(system_bluetooth_GetAdapterSuccessResult, discovering), sizeof(FtBool) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_GetAdapterSuccessResult_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_GetAdapterSuccessResult) },
    .members = system_bluetooth_GetAdapterSuccessResult_struct_members
};

system_bluetooth_GetAdapterSuccessResult* system_bluetoothMallocGetAdapterSuccessResult () {
    return (system_bluetooth_GetAdapterSuccessResult*)FeatureMalloc(
        sizeof(system_bluetooth_GetAdapterSuccessResult), FT_MK_COMPLEX_REF(&system_bluetooth_GetAdapterSuccessResult_struct_type));
}


/****** for JIDL callback 'getAdapterStateSuccess' ******/
static const FeatureType system_bluetooth_getAdapterStateSuccess_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_GetAdapterSuccessResult_struct_type),
    FT_PARAM_END
};

static const CallbackType system_bluetooth_getAdapterStateSuccess_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_getAdapterStateSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'getAdapterStateFail' ******/
static const FeatureType system_bluetooth_getAdapterStateFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_getAdapterStateFail_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_getAdapterStateFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'getAdapterStateComplete' ******/
static const FeatureType system_bluetooth_getAdapterStateComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_getAdapterStateComplete_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_getAdapterStateComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'GetAdapterStateParams' ******/
static ObjectMember system_bluetooth_GetAdapterStateParams_struct_members[] = {
    { "success", FT_MK_COMPLEX(&system_bluetooth_getAdapterStateSuccess_callback_type), offsetof(system_bluetooth_GetAdapterStateParams, success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_getAdapterStateFail_callback_type), offsetof(system_bluetooth_GetAdapterStateParams, fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_getAdapterStateComplete_callback_type), offsetof(system_bluetooth_GetAdapterStateParams, complete), sizeof(FtCallbackId) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_GetAdapterStateParams_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_GetAdapterStateParams) },
    .members = system_bluetooth_GetAdapterStateParams_struct_members
};

system_bluetooth_GetAdapterStateParams* system_bluetoothMallocGetAdapterStateParams () {
    return (system_bluetooth_GetAdapterStateParams*)FeatureMalloc(
        sizeof(system_bluetooth_GetAdapterStateParams), FT_MK_COMPLEX_REF(&system_bluetooth_GetAdapterStateParams_struct_type));
}


/****** for JIDL function 'getAdapterState' ******/
static const FeatureType system_bluetooth_getAdapterState_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_GetAdapterStateParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_getAdapterState_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_wrap_getAdapterState) },
    .parameters = system_bluetooth_getAdapterState_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'adapterStateCallbackData' ******/
static ObjectMember system_bluetooth_adapterStateCallbackData_struct_members[] = {
    { "available", FT_BOOLEAN, offsetof(system_bluetooth_adapterStateCallbackData, available), sizeof(FtBool) },
    { "discovering", FT_BOOLEAN, offsetof(system_bluetooth_adapterStateCallbackData, discovering), sizeof(FtBool) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_adapterStateCallbackData_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_adapterStateCallbackData) },
    .members = system_bluetooth_adapterStateCallbackData_struct_members
};

system_bluetooth_adapterStateCallbackData* system_bluetoothMallocadapterStateCallbackData () {
    return (system_bluetooth_adapterStateCallbackData*)FeatureMalloc(
        sizeof(system_bluetooth_adapterStateCallbackData), FT_MK_COMPLEX_REF(&system_bluetooth_adapterStateCallbackData_struct_type));
}


/****** for JIDL callback 'adapterStateChange' ******/
static const FeatureType system_bluetooth_adapterStateChange_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_adapterStateCallbackData_struct_type),
    FT_PARAM_END
};

static const CallbackType system_bluetooth_adapterStateChange_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_adapterStateChange_parameters,
    .return_type = FT_VOID
};


/****** for JIDL property 'onadapterstatechange' ******/
static const MemberAccessor system_bluetooth_onadapterstatechange_member_accessor = {
    .getter = { .callback = FFI_FN(system_bluetooth_get_onadapterstatechange) },
    .setter = { .callback = FFI_FN(system_bluetooth_set_onadapterstatechange) },
    .type = FT_MK_COMPLEX(&system_bluetooth_adapterStateChange_callback_type),
};


// members
static const Member system_bluetooth_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "openAdapter",
        .method = &system_bluetooth_openAdapter_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "closeAdapter",
        .method = &system_bluetooth_closeAdapter_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getAdapterState",
        .method = &system_bluetooth_getAdapterState_member_method,
    },
    {
        .type = MEMBER_ACCESSOR,
        .name = "onadapterstatechange",
        .accessor = &system_bluetooth_onadapterstatechange_member_accessor,
    },
};

// callbacks
static const struct FeatureCallbacks system_bluetooth_callbacks = {
    system_bluetooth_onRegister,
    system_bluetooth_onCreate,
    system_bluetooth_onRequired,
    system_bluetooth_onDetached,
    system_bluetooth_onDestroy,
    system_bluetooth_onUnregister
};

static const FeatureDescription system_bluetooth_desc = {
    .version = 1,
    .name = "system.bluetooth",
    .description = "system.bluetooth",
    { .dynamic = false },
    .native_callbacks = &system_bluetooth_callbacks,
    .member_count = countof(system_bluetooth_members),
    .members = system_bluetooth_members,
};

QAPPFEATURE_INIT(system_bluetooth)
{
    return FeatureRegisterFeature(handle, &system_bluetooth_desc);
}
/* clang-format on */
