/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#include "bluetooth.h"
#include "bt_adapter.h"
#include "feature_adapter.h"
#include "feature_a2dpsink.h"
#include "feature_exports.h"
#include "feature_log.h"
#include "system_bluetooth.h"
#include "system_bluetooth_bt.h"

#define file_tag "system_bluetooth"

static bt_instance_t* g_feature_ins = NULL;
static void* adapter_callback = NULL;
static adapter_feature_callbacks_t g_feature_callbacks = {};

static char* StringToFtString(const char* str)
{
    int len = strlen(str);
    char* ftStr = (char*)FeatureMalloc(len + 1, FT_CHAR);
    strcpy(ftStr, str);
    return ftStr;
}

static void on_adapter_state_changed_cb(void* cookie, bt_adapter_state_t state)
{
    if (state == BT_ADAPTER_STATE_ON) {
#ifdef CONFIG_BLUETOOTH_A2DP_SINK
        a2dp_sink_feature_init(feature_bluetooth_get_instance());
#endif
    } else if (state == BT_ADAPTER_STATE_TURNING_OFF) {
#ifdef CONFIG_BLUETOOTH_A2DP_SINK
        a2dp_sink_feature_uninit(feature_bluetooth_get_instance());
#endif
    }

    if (g_feature_callbacks.on_adapter_state_changed_cb.feature == NULL)
        return;
    if (state != BT_ADAPTER_STATE_ON && state != BT_ADAPTER_STATE_OFF)
        return;

    system_bluetooth_adapterStateCallbackData* data = system_bluetoothMallocadapterStateCallbackData();
    data->available = state == BT_ADAPTER_STATE_ON;
    data->discovering = bt_adapter_is_discovering(feature_bluetooth_get_instance());
    FEATURE_LOG_ERROR("feature:%p, callbackId:%d",
        g_feature_callbacks.on_discovery_result_cb.feature,
        g_feature_callbacks.on_discovery_result_cb.callbackId);
    if (!FeatureInvokeCallback(g_feature_callbacks.on_adapter_state_changed_cb.feature,
            g_feature_callbacks.on_adapter_state_changed_cb.callbackId, data)) {
        FEATURE_LOG_ERROR("feature:%p, callbackId:%d, invoke on adapter state change callback failed!",
            g_feature_callbacks.on_adapter_state_changed_cb.feature,
            g_feature_callbacks.on_adapter_state_changed_cb.callbackId);
    }
}

static void on_discovery_state_changed_cb(void* cookie, bt_discovery_state_t state)
{
    if (g_feature_callbacks.on_adapter_state_changed_cb.feature == NULL)
        return;

    system_bluetooth_adapterStateCallbackData* data = system_bluetoothMallocadapterStateCallbackData();
    data->available = bt_adapter_get_state(feature_bluetooth_get_instance()) == BT_ADAPTER_STATE_ON;
    data->discovering = state == BT_DISCOVERY_STATE_STARTED;

    if (!FeatureInvokeCallback(g_feature_callbacks.on_adapter_state_changed_cb.feature,
            g_feature_callbacks.on_adapter_state_changed_cb.callbackId, data)) {
        FEATURE_LOG_ERROR("feature:%p, callbackId:%d, invoke on adapter state change callback failed!",
            g_feature_callbacks.on_adapter_state_changed_cb.feature,
            g_feature_callbacks.on_adapter_state_changed_cb.callbackId);
    }
}

static void on_discovery_result_cb(void* cookie, bt_discovery_result_t* result)
{
    if (g_feature_callbacks.on_discovery_result_cb.feature == NULL)
        return;

    system_bluetooth_bt_DiscoveryResultCallbackData* data = system_bluetooth_btMallocDiscoveryResultCallbackData();
    data->name = StringToFtString(result->name);
    char addr_str[BT_ADDR_STR_LENGTH] = { 0 };
    bt_addr_ba2str(&result->addr, addr_str);
    data->deviceId = StringToFtString(addr_str);
    data->cod = result->cod;
    data->rssi = -result->rssi;

    if (!FeatureInvokeCallback(g_feature_callbacks.on_discovery_result_cb.feature,
            g_feature_callbacks.on_discovery_result_cb.callbackId, data)) {
        FEATURE_LOG_ERROR("feature:%p, callbackId:%d, invoke discoveryresult callback failed!",
            g_feature_callbacks.on_discovery_result_cb.feature,
            g_feature_callbacks.on_discovery_result_cb.callbackId);
    }
}

static void on_pair_request_cb(void* cookie, bt_address_t* addr)
{
    bt_device_pair_request_reply(feature_bluetooth_get_instance(), addr, true);
}

static void on_connect_request_cb(void* cookie, bt_address_t* addr)
{
    bt_device_connect_request_reply(feature_bluetooth_get_instance(), addr, true);
}


static void on_bond_state_changed_cb(void* cookie, bt_address_t* addr, bt_transport_t transport, bond_state_t state, bool is_ctkd)
{
    if (g_feature_callbacks.on_bond_state_changed_cb.feature == NULL)
        return;

    if (transport == BT_TRANSPORT_BREDR) {
        system_bluetooth_bt_onBondStateChangeData* data = system_bluetooth_btMalloconBondStateChangeData();
        char addr_str[BT_ADDR_STR_LENGTH] = { 0 };
        bt_addr_ba2str(addr, addr_str);
        data->deviceId = StringToFtString(addr_str);
        data->bondState = state;

        if (!FeatureInvokeCallback(g_feature_callbacks.on_bond_state_changed_cb.feature,
                g_feature_callbacks.on_bond_state_changed_cb.callbackId, data)) {
            FEATURE_LOG_ERROR("feature:%p, invoke bond state change callback failed!",
            g_feature_callbacks.on_bond_state_changed_cb.feature);
        }
    }
}


const static adapter_callbacks_t g_adapter_cbs = {
    .on_adapter_state_changed = on_adapter_state_changed_cb,
    .on_discovery_state_changed = on_discovery_state_changed_cb,
    .on_discovery_result = on_discovery_result_cb,
    .on_pair_request = on_pair_request_cb,
    .on_connect_request = on_connect_request_cb,
    .on_bond_state_changed = on_bond_state_changed_cb,
};
void clean_feature_adapter_callback(void* feature)
{
    g_feature_callbacks.on_adapter_state_changed_cb.feature = NULL;
    g_feature_callbacks.on_adapter_state_changed_cb.callbackId = 0;
    g_feature_callbacks.on_discovery_result_cb.feature = NULL;
    g_feature_callbacks.on_discovery_result_cb.callbackId = 0;
    g_feature_callbacks.on_bond_state_changed_cb.feature = NULL;
    g_feature_callbacks.on_bond_state_changed_cb.callbackId = 0;
}

void bluetooth_init_ins()
{
    g_feature_ins = bluetooth_create_instance();
    adapter_callback = bt_adapter_register_callback(g_feature_ins, &g_adapter_cbs);
}

void bluetooth_uninit_ins()
{
    bt_adapter_unregister_callback(feature_bluetooth_get_instance(), adapter_callback);
    bluetooth_delete_instance(g_feature_ins);
    g_feature_ins = NULL;
}

bt_instance_t* feature_bluetooth_get_instance()
{
    return g_feature_ins;
}

adapter_feature_callbacks_t* get_adapter_cbs()
{
    return &g_feature_callbacks;
}

bool bt_feature_allocator(void** data, uint32_t size)
{
    *data = malloc(size);
    if (!(*data))
        return false;

    return true;
}

// FeatureCallbacks to be implemented
void system_bluetooth_onRegister(const char* feature_name)
{
    bluetooth_init_ins();
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    clean_feature_adapter_callback(handle);
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_onUnregister(const char* feature_name)
{
    bluetooth_uninit_ins();
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_wrap_openAdapter(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_OpenAdapterParams* params)
{
    bt_status_t status = bt_adapter_enable(feature_bluetooth_get_instance());
    if (status == BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->success)) {
            FEATURE_LOG_ERROR("invoke success callback failed, feature is %p, params->success is %d!",feature, params->success);
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->fail, "enable fail!", status)) {
            FEATURE_LOG_ERROR("invoke fail callback failed!");
            return;
        }
    }
    if (!FeatureInvokeCallback(feature, params->complete)) {
        FEATURE_LOG_ERROR("invoke fail callback failed!");
        return;
    }
}

void system_bluetooth_wrap_closeAdapter(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_CloseAdapterParams* params)
{
    bt_status_t status = bt_adapter_disable(feature_bluetooth_get_instance());
    if (status == BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->success)) {
            FEATURE_LOG_ERROR("invoke success callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->fail, "enable fail!", status)) {
            FEATURE_LOG_ERROR("invoke fail callback failed!");
            return;
        }
    }
    if (!FeatureInvokeCallback(feature, params->complete)) {
        FEATURE_LOG_ERROR("invoke fail callback failed!");
        return;
    }
}

void system_bluetooth_wrap_getAdapterState(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_GetAdapterStateParams* params)
{
    bt_instance_t* ins = feature_bluetooth_get_instance();
    bt_adapter_state_t state = bt_adapter_get_state(ins);
    bool is_discovering = bt_adapter_is_discovering(ins);
    system_bluetooth_GetAdapterSuccessResult success_result = { state == BT_ADAPTER_STATE_ON, is_discovering };
    if (!FeatureInvokeCallback(feature, params->success, success_result)) {
        FEATURE_LOG_ERROR("invoke success callback failed!");
        return;
    }
    if (!FeatureInvokeCallback(feature, params->complete)) {
        FEATURE_LOG_ERROR("invoke fail callback failed!");
        return;
    }
}

FtCallbackId system_bluetooth_get_onadapterstatechange(void* feature, union AppendData append_data)
{
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    return adaptercallbacks->on_adapter_state_changed_cb.callbackId;
}

void system_bluetooth_set_onadapterstatechange(void* feature, union AppendData append_data, FtCallbackId onadapterstatechange)
{
    FEATURE_LOG_INFO("set onadapterstatechange feature: %p, callbackId: %d\n", feature, onadapterstatechange);
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    adaptercallbacks->on_adapter_state_changed_cb.feature = feature;
    adaptercallbacks->on_adapter_state_changed_cb.callbackId = onadapterstatechange;
}
