/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "system_bluetooth_bt.h"
#include "ajs_features_init.h"
#include "feature_description.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL callback 'startDiscoverySuccess' ******/
static const FeatureType system_bluetooth_bt_startDiscoverySuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_startDiscoverySuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_startDiscoverySuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'startDiscoveryFail' ******/
static const FeatureType system_bluetooth_bt_startDiscoveryFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_startDiscoveryFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_startDiscoveryFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'startDiscoveryComplete' ******/
static const FeatureType system_bluetooth_bt_startDiscoveryComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_startDiscoveryComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_startDiscoveryComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'StartDiscoveryParams' ******/
static ObjectMember system_bluetooth_bt_StartDiscoveryParams_struct_members[] = {
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_startDiscoverySuccess_callback_type), offsetof(system_bluetooth_bt_StartDiscoveryParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_startDiscoveryFail_callback_type), offsetof(system_bluetooth_bt_StartDiscoveryParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_startDiscoveryComplete_callback_type), offsetof(system_bluetooth_bt_StartDiscoveryParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_StartDiscoveryParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_StartDiscoveryParams) },
    .members = system_bluetooth_bt_StartDiscoveryParams_struct_members
};

system_bluetooth_bt_StartDiscoveryParams* system_bluetooth_btMallocStartDiscoveryParams () {
    return (system_bluetooth_bt_StartDiscoveryParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_StartDiscoveryParams), FT_MK_COMPLEX(&system_bluetooth_bt_StartDiscoveryParams_struct_type));
}


/****** for JIDL function 'startDiscovery' ******/
static const FeatureType system_bluetooth_bt_startDiscovery_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_StartDiscoveryParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_startDiscovery_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_startDiscovery) },
    .parameters = system_bluetooth_bt_startDiscovery_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'stopDiscoverySuccess' ******/
static const FeatureType system_bluetooth_bt_stopDiscoverySuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_stopDiscoverySuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_stopDiscoverySuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'stopDiscoveryFail' ******/
static const FeatureType system_bluetooth_bt_stopDiscoveryFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_stopDiscoveryFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_stopDiscoveryFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'stopDiscoveryComplete' ******/
static const FeatureType system_bluetooth_bt_stopDiscoveryComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_stopDiscoveryComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_stopDiscoveryComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'StopDiscoveryParams' ******/
static ObjectMember system_bluetooth_bt_StopDiscoveryParams_struct_members[] = {
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_stopDiscoverySuccess_callback_type), offsetof(system_bluetooth_bt_StopDiscoveryParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_stopDiscoveryFail_callback_type), offsetof(system_bluetooth_bt_StopDiscoveryParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_stopDiscoveryComplete_callback_type), offsetof(system_bluetooth_bt_StopDiscoveryParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_StopDiscoveryParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_StopDiscoveryParams) },
    .members = system_bluetooth_bt_StopDiscoveryParams_struct_members
};

system_bluetooth_bt_StopDiscoveryParams* system_bluetooth_btMallocStopDiscoveryParams () {
    return (system_bluetooth_bt_StopDiscoveryParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_StopDiscoveryParams), FT_MK_COMPLEX(&system_bluetooth_bt_StopDiscoveryParams_struct_type));
}


/****** for JIDL function 'stopDiscovery' ******/
static const FeatureType system_bluetooth_bt_stopDiscovery_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_StopDiscoveryParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_stopDiscovery_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_stopDiscovery) },
    .parameters = system_bluetooth_bt_stopDiscovery_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL struct 'DiscoveryResultCallbackData' ******/
static ObjectMember system_bluetooth_bt_DiscoveryResultCallbackData_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_DiscoveryResultCallbackData, _deviceId), sizeof(FtString) },
    { "name", FT_STRING, offsetof(system_bluetooth_bt_DiscoveryResultCallbackData, _name), sizeof(FtString) },
    { "cod", FT_UINT32, offsetof(system_bluetooth_bt_DiscoveryResultCallbackData, _cod), sizeof(unsigned int) },
    { "rssi", FT_UINT32, offsetof(system_bluetooth_bt_DiscoveryResultCallbackData, _rssi), sizeof(unsigned int) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_DiscoveryResultCallbackData_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_DiscoveryResultCallbackData) },
    .members = system_bluetooth_bt_DiscoveryResultCallbackData_struct_members
};

system_bluetooth_bt_DiscoveryResultCallbackData* system_bluetooth_btMallocDiscoveryResultCallbackData () {
    return (system_bluetooth_bt_DiscoveryResultCallbackData*)FeatureMalloc(
        sizeof(system_bluetooth_bt_DiscoveryResultCallbackData), FT_MK_COMPLEX(&system_bluetooth_bt_DiscoveryResultCallbackData_struct_type));
}


/****** for JIDL callback 'discoveryResultChange' ******/
static const FeatureType system_bluetooth_bt_discoveryResultChange_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_DiscoveryResultCallbackData_struct_type),
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_discoveryResultChange_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_discoveryResultChange_parameters,
    .return_type = FT_VOID
};


/****** for JIDL property 'discoveryresult' ******/
static const MemberAccessor system_bluetooth_bt_discoveryresult_member_accessor = {
    .getter = { .callback = FFI_FN(system_bluetooth_bt_get_discoveryresult) },
    .setter = { .callback = FFI_FN(system_bluetooth_bt_set_discoveryresult) },
    .type = FT_MK_COMPLEX(&system_bluetooth_bt_discoveryResultChange_callback_type),
};


/****** for JIDL callback 'connectProfilesSuccess' ******/
static const FeatureType system_bluetooth_bt_connectProfilesSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_connectProfilesSuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_connectProfilesSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'connectProfilesFail' ******/
static const FeatureType system_bluetooth_bt_connectProfilesFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_connectProfilesFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_connectProfilesFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'connectProfilesComplete' ******/
static const FeatureType system_bluetooth_bt_connectProfilesComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_connectProfilesComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_connectProfilesComplete_parameters,
    .return_type = FT_VOID
};


static const ArrayType system_bluetooth_bt_int_array = {
    .header = { .type = COMPLEX_ARRAY, .size = sizeof(FtArray) },
    .element_type = FT_INT
};

FtArray* system_bluetooth_bt_malloc_int_array() {
    return (FtArray*)FeatureMalloc(
        sizeof(FtArray), FT_MK_COMPLEX(&system_bluetooth_bt_int_array));
}

/****** for JIDL struct 'ConnectProfilesParams' ******/
static ObjectMember system_bluetooth_bt_ConnectProfilesParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_ConnectProfilesParams, _deviceId), sizeof(FtString) },
    { "profiles", FT_MK_COMPLEX_REF(&system_bluetooth_bt_int_array), offsetof(system_bluetooth_bt_ConnectProfilesParams, _profiles), sizeof(FtArray*) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_connectProfilesSuccess_callback_type), offsetof(system_bluetooth_bt_ConnectProfilesParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_connectProfilesFail_callback_type), offsetof(system_bluetooth_bt_ConnectProfilesParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_connectProfilesComplete_callback_type), offsetof(system_bluetooth_bt_ConnectProfilesParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_ConnectProfilesParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_ConnectProfilesParams) },
    .members = system_bluetooth_bt_ConnectProfilesParams_struct_members
};

system_bluetooth_bt_ConnectProfilesParams* system_bluetooth_btMallocConnectProfilesParams () {
    return (system_bluetooth_bt_ConnectProfilesParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_ConnectProfilesParams), FT_MK_COMPLEX(&system_bluetooth_bt_ConnectProfilesParams_struct_type));
}


/****** for JIDL function 'connectProfiles' ******/
static const FeatureType system_bluetooth_bt_connectProfiles_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_ConnectProfilesParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_connectProfiles_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_connectProfiles) },
    .parameters = system_bluetooth_bt_connectProfiles_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'disconnectProfilesSuccess' ******/
static const FeatureType system_bluetooth_bt_disconnectProfilesSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectProfilesSuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectProfilesSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'disconnectProfilesFail' ******/
static const FeatureType system_bluetooth_bt_disconnectProfilesFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectProfilesFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectProfilesFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'disconnectProfilesComplete' ******/
static const FeatureType system_bluetooth_bt_disconnectProfilesComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectProfilesComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectProfilesComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'DisconnectProfilesParams' ******/
static ObjectMember system_bluetooth_bt_DisconnectProfilesParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_DisconnectProfilesParams, _deviceId), sizeof(FtString) },
    { "profiles", FT_MK_COMPLEX_REF(&system_bluetooth_bt_int_array), offsetof(system_bluetooth_bt_DisconnectProfilesParams, _profiles), sizeof(FtArray*) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectProfilesSuccess_callback_type), offsetof(system_bluetooth_bt_DisconnectProfilesParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectProfilesFail_callback_type), offsetof(system_bluetooth_bt_DisconnectProfilesParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectProfilesComplete_callback_type), offsetof(system_bluetooth_bt_DisconnectProfilesParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_DisconnectProfilesParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_DisconnectProfilesParams) },
    .members = system_bluetooth_bt_DisconnectProfilesParams_struct_members
};

system_bluetooth_bt_DisconnectProfilesParams* system_bluetooth_btMallocDisconnectProfilesParams () {
    return (system_bluetooth_bt_DisconnectProfilesParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_DisconnectProfilesParams), FT_MK_COMPLEX(&system_bluetooth_bt_DisconnectProfilesParams_struct_type));
}


/****** for JIDL function 'disconnectProfiles' ******/
static const FeatureType system_bluetooth_bt_disconnectProfiles_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_DisconnectProfilesParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_disconnectProfiles_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_disconnectProfiles) },
    .parameters = system_bluetooth_bt_disconnectProfiles_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL callback 'disconnectSuccess' ******/
static const FeatureType system_bluetooth_bt_disconnectSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectSuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'disconnectFail' ******/
static const FeatureType system_bluetooth_bt_disconnectFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'disconnectComplete' ******/
static const FeatureType system_bluetooth_bt_disconnectComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_disconnectComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_disconnectComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'DisconnectParams' ******/
static ObjectMember system_bluetooth_bt_DisconnectParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_DisconnectParams, _deviceId), sizeof(FtString) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectSuccess_callback_type), offsetof(system_bluetooth_bt_DisconnectParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectFail_callback_type), offsetof(system_bluetooth_bt_DisconnectParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_disconnectComplete_callback_type), offsetof(system_bluetooth_bt_DisconnectParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_DisconnectParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_DisconnectParams) },
    .members = system_bluetooth_bt_DisconnectParams_struct_members
};

system_bluetooth_bt_DisconnectParams* system_bluetooth_btMallocDisconnectParams () {
    return (system_bluetooth_bt_DisconnectParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_DisconnectParams), FT_MK_COMPLEX(&system_bluetooth_bt_DisconnectParams_struct_type));
}


/****** for JIDL function 'disconnect' ******/
static const FeatureType system_bluetooth_bt_disconnect_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_DisconnectParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_disconnect_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_disconnect) },
    .parameters = system_bluetooth_bt_disconnect_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'getConnectState' ******/
static const FeatureType system_bluetooth_bt_getConnectState_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_getConnectState_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getConnectState) },
    .parameters = system_bluetooth_bt_getConnectState_parameters,
    .return_type = FT_BOOLEAN,
};


/****** for JIDL struct 'connectedDevice' ******/
static ObjectMember system_bluetooth_bt_connectedDevice_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_connectedDevice, _deviceId), sizeof(FtString) },
    { "name", FT_STRING, offsetof(system_bluetooth_bt_connectedDevice, _name), sizeof(FtString) },
    { "cod", FT_INT, offsetof(system_bluetooth_bt_connectedDevice, _cod), sizeof(FtInt) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_connectedDevice_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_connectedDevice) },
    .members = system_bluetooth_bt_connectedDevice_struct_members
};

system_bluetooth_bt_connectedDevice* system_bluetooth_btMallocconnectedDevice () {
    return (system_bluetooth_bt_connectedDevice*)FeatureMalloc(
        sizeof(system_bluetooth_bt_connectedDevice), FT_MK_COMPLEX(&system_bluetooth_bt_connectedDevice_struct_type));
}


/****** for JIDL function 'getConnectedDevices' ******/
static const FeatureType system_bluetooth_bt_getConnectedDevices_parameters[] = {
    FT_PARAM_END
};

static const ArrayType system_bluetooth_bt_string_array = {
    .header = { .type = COMPLEX_ARRAY, .size = sizeof(FtArray) },
    .element_type = FT_STRING
};

FtArray* system_bluetooth_bt_malloc_string_array() {
    return (FtArray*)FeatureMalloc(
        sizeof(FtArray), FT_MK_COMPLEX(&system_bluetooth_bt_string_array));
}

static const MemberMethod system_bluetooth_bt_getConnectedDevices_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getConnectedDevices) },
    .parameters = system_bluetooth_bt_getConnectedDevices_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_bluetooth_bt_string_array),
};


/****** for JIDL function 'getBondedDevices' ******/
static const FeatureType system_bluetooth_bt_getBondedDevices_parameters[] = {
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_getBondedDevices_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getBondedDevices) },
    .parameters = system_bluetooth_bt_getBondedDevices_parameters,
    .return_type = FT_MK_COMPLEX_REF(&system_bluetooth_bt_string_array),
};


/****** for JIDL struct 'onBondStateChangeData' ******/
static ObjectMember system_bluetooth_bt_onBondStateChangeData_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_onBondStateChangeData, _deviceId), sizeof(FtString) },
    { "bondState", FT_INT, offsetof(system_bluetooth_bt_onBondStateChangeData, _bondState), sizeof(FtInt) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_onBondStateChangeData_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_onBondStateChangeData) },
    .members = system_bluetooth_bt_onBondStateChangeData_struct_members
};

system_bluetooth_bt_onBondStateChangeData* system_bluetooth_btMalloconBondStateChangeData () {
    return (system_bluetooth_bt_onBondStateChangeData*)FeatureMalloc(
        sizeof(system_bluetooth_bt_onBondStateChangeData), FT_MK_COMPLEX(&system_bluetooth_bt_onBondStateChangeData_struct_type));
}


/****** for JIDL callback 'onBondStateChangeCallback' ******/
static const FeatureType system_bluetooth_bt_onBondStateChangeCallback_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_onBondStateChangeData_struct_type),
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_onBondStateChangeCallback_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_onBondStateChangeCallback_parameters,
    .return_type = FT_VOID
};


/****** for JIDL property 'onbondstatechange' ******/
static const MemberAccessor system_bluetooth_bt_onbondstatechange_member_accessor = {
    .getter = { .callback = FFI_FN(system_bluetooth_bt_get_onbondstatechange) },
    .setter = { .callback = FFI_FN(system_bluetooth_bt_set_onbondstatechange) },
    .type = FT_MK_COMPLEX(&system_bluetooth_bt_onBondStateChangeCallback_callback_type),
};


/****** for JIDL callback 'removeBondedSuccess' ******/
static const FeatureType system_bluetooth_bt_removeBondedSuccess_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_removeBondedSuccess_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_removeBondedSuccess_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'removeBondedFail' ******/
static const FeatureType system_bluetooth_bt_removeBondedFail_parameters[] = {
    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_removeBondedFail_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_removeBondedFail_parameters,
    .return_type = FT_VOID
};


/****** for JIDL callback 'removeBondedComplete' ******/
static const FeatureType system_bluetooth_bt_removeBondedComplete_parameters[] = {
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_removeBondedComplete_callback_type {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_removeBondedComplete_parameters,
    .return_type = FT_VOID
};


/****** for JIDL struct 'RemoveBondedParams' ******/
static ObjectMember system_bluetooth_bt_RemoveBondedParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_RemoveBondedParams, _deviceId), sizeof(FtString) },
    { "success", FT_MK_COMPLEX(&system_bluetooth_bt_removeBondedSuccess_callback_type), offsetof(system_bluetooth_bt_RemoveBondedParams, _success), sizeof(FtCallbackId) },
    { "fail", FT_MK_COMPLEX(&system_bluetooth_bt_removeBondedFail_callback_type), offsetof(system_bluetooth_bt_RemoveBondedParams, _fail), sizeof(FtCallbackId) },
    { "complete", FT_MK_COMPLEX(&system_bluetooth_bt_removeBondedComplete_callback_type), offsetof(system_bluetooth_bt_RemoveBondedParams, _complete), sizeof(FtCallbackId) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_RemoveBondedParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_RemoveBondedParams) },
    .members = system_bluetooth_bt_RemoveBondedParams_struct_members
};

system_bluetooth_bt_RemoveBondedParams* system_bluetooth_btMallocRemoveBondedParams () {
    return (system_bluetooth_bt_RemoveBondedParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_RemoveBondedParams), FT_MK_COMPLEX(&system_bluetooth_bt_RemoveBondedParams_struct_type));
}


/****** for JIDL function 'removeBondedDevice' ******/
static const FeatureType system_bluetooth_bt_removeBondedDevice_parameters[] = {
    FT_MK_COMPLEX_REF(&system_bluetooth_bt_RemoveBondedParams_struct_type),
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_removeBondedDevice_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_removeBondedDevice) },
    .parameters = system_bluetooth_bt_removeBondedDevice_parameters,
    .return_type = FT_VOID,
};


/****** for JIDL function 'setScanMode' ******/
static const FeatureType system_bluetooth_bt_setScanMode_parameters[] = {
    FT_INT,
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_setScanMode_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_setScanMode) },
    .parameters = system_bluetooth_bt_setScanMode_parameters,
    .return_type = FT_BOOLEAN,
};


/****** for JIDL function 'getScanMode' ******/
static const FeatureType system_bluetooth_bt_getScanMode_parameters[] = {
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_getScanMode_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getScanMode) },
    .parameters = system_bluetooth_bt_getScanMode_parameters,
    .return_type = FT_INT,
};


/****** for JIDL struct 'GetDeviceNameParams' ******/
static ObjectMember system_bluetooth_bt_GetDeviceNameParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_GetDeviceNameParams, _deviceId), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_GetDeviceNameParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_GetDeviceNameParams) },
    .members = system_bluetooth_bt_GetDeviceNameParams_struct_members
};

system_bluetooth_bt_GetDeviceNameParams* system_bluetooth_btMallocGetDeviceNameParams () {
    return (system_bluetooth_bt_GetDeviceNameParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_GetDeviceNameParams), FT_MK_COMPLEX(&system_bluetooth_bt_GetDeviceNameParams_struct_type));
}


/****** for JIDL function 'getDeviceName' ******/
static const FeatureType system_bluetooth_bt_getDeviceName_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_getDeviceName_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getDeviceName) },
    .parameters = system_bluetooth_bt_getDeviceName_parameters,
    .return_type = FT_STRING,
};


/****** for JIDL struct 'GetDeviceClassParams' ******/
static ObjectMember system_bluetooth_bt_GetDeviceClassParams_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_GetDeviceClassParams, _deviceId), sizeof(FtString) },
    { nullptr },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_GetDeviceClassParams_struct_type {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_GetDeviceClassParams) },
    .members = system_bluetooth_bt_GetDeviceClassParams_struct_members
};

system_bluetooth_bt_GetDeviceClassParams* system_bluetooth_btMallocGetDeviceClassParams () {
    return (system_bluetooth_bt_GetDeviceClassParams*)FeatureMalloc(
        sizeof(system_bluetooth_bt_GetDeviceClassParams), FT_MK_COMPLEX(&system_bluetooth_bt_GetDeviceClassParams_struct_type));
}


/****** for JIDL function 'getDeviceClass' ******/
static const FeatureType system_bluetooth_bt_getDeviceClass_parameters[] = {
    FT_STRING,
    FT_PARAM_END
};

static const MemberMethod system_bluetooth_bt_getDeviceClass_member_method = {
    .func = { .callback = FFI_FN(system_bluetooth_bt_wrap_getDeviceClass) },
    .parameters = system_bluetooth_bt_getDeviceClass_parameters,
    .return_type = FT_UINT32,
};


// members
static const Member system_bluetooth_bt_members[] = {
    {
        .type = MEMBER_METHOD,
        .name = "startDiscovery",
        .method = system_bluetooth_bt_startDiscovery_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "stopDiscovery",
        .method = system_bluetooth_bt_stopDiscovery_member_method,
    },
    {
        .type = MEMBER_ACCESSOR,
        .name = "discoveryresult",
        .accessor = system_bluetooth_bt_discoveryresult_member_accessor,
    },
    {
        .type = MEMBER_METHOD,
        .name = "connectProfiles",
        .method = system_bluetooth_bt_connectProfiles_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "disconnectProfiles",
        .method = system_bluetooth_bt_disconnectProfiles_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "disconnect",
        .method = system_bluetooth_bt_disconnect_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getConnectState",
        .method = system_bluetooth_bt_getConnectState_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getConnectedDevices",
        .method = system_bluetooth_bt_getConnectedDevices_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getBondedDevices",
        .method = system_bluetooth_bt_getBondedDevices_member_method,
    },
    {
        .type = MEMBER_ACCESSOR,
        .name = "onbondstatechange",
        .accessor = system_bluetooth_bt_onbondstatechange_member_accessor,
    },
    {
        .type = MEMBER_METHOD,
        .name = "removeBondedDevice",
        .method = system_bluetooth_bt_removeBondedDevice_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "setScanMode",
        .method = system_bluetooth_bt_setScanMode_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getScanMode",
        .method = system_bluetooth_bt_getScanMode_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getDeviceName",
        .method = system_bluetooth_bt_getDeviceName_member_method,
    },
    {
        .type = MEMBER_METHOD,
        .name = "getDeviceClass",
        .method = system_bluetooth_bt_getDeviceClass_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_bluetooth_bt_callbacks {
    system_bluetooth_bt_onRegister,
    system_bluetooth_bt_onCreate,
    system_bluetooth_bt_onRequired,
    system_bluetooth_bt_onDetached,
    system_bluetooth_bt_onDestroy,
    system_bluetooth_bt_onUnregister
};

static const FeatureDescription system_bluetooth_bt_desc = {
    .version = 1,
    .name = "system.bluetooth.bt",
    .description = "system.bluetooth.bt",
    { .dynamic = false },
    .native_callbacks = &system_bluetooth_bt_callbacks,
    .member_count = countof(system_bluetooth_bt_members),
    .members = system_bluetooth_bt_members,
};

QAPPFEATURE_INIT(system_bluetooth_bt)
{
    return mgr->registerFeature(features, &system_bluetooth_bt_desc);
}
/* clang-format on */
