/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#include <string>
#include "bt_a2dp_sink.h"
#include "feature_a2dpsink.h"
#include "system_bluetooth_bt_a2dpsink.h"

#define file_tag "system_bluetooth_bt_a2dpsnk"

static a2dp_sink_feature_callbacks_t g_feature_a2dp_sink_callbacks = {};
static void* sink_cbks_cookie = nullptr;

static char* StringToFtString(std::string str)
{
    int len = str.length();
    char* ftStr = (char*)FeatureMalloc(len + 1, FT_CHAR);
    strcpy(ftStr, str.c_str());
    return ftStr;
}

static void a2dp_sink_connection_state_cb(void* cookie, bt_address_t* addr, profile_connection_state_t state)
{
    system_bluetooth_bt_a2dpsink_OnConnectStateChangeData* data = system_bluetooth_bt_a2dpsinkMallocOnConnectStateChangeData();
    char addr_str[BT_ADDR_STR_LENGTH] = { 0 };
    bt_addr_ba2str(addr, addr_str);
    data->_deviceId = StringToFtString(addr_str);
    data->_connectState = state;
    for (auto feature : g_feature_a2dp_sink_callbacks.a2dp_sink_connection_state_cbs) {
        if (!FeatureInvokeCallback(feature.first, feature.second, data)) {
            FEATURE_LOG_ERROR("feature:%p, invoke discoveryresult callback failed!", feature.first);
        }
    }
}

static void a2dp_sink_audio_state_cb(void* cookie, bt_address_t* addr, a2dp_audio_state_t state)
{
}

static void a2dp_sink_audio_config_cb(void* cookie, bt_address_t* addr)
{
}

static const a2dp_sink_callbacks_t a2dp_sink_cbs = {
    sizeof(a2dp_sink_cbs),
    a2dp_sink_connection_state_cb,
    a2dp_sink_audio_state_cb,
    a2dp_sink_audio_config_cb,
};

void system_bluetooth_bt_a2dpsink_onRegister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_bluetooth_bt_a2dpsink_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_bluetooth_bt_a2dpsink_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_bluetooth_bt_a2dpsink_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    g_feature_a2dp_sink_callbacks.a2dp_sink_connection_state_cbs.erase(handle);
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_bluetooth_bt_a2dpsink_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}
void system_bluetooth_bt_a2dpsink_onUnregister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

FtCallbackId system_bluetooth_bt_a2dpsink_get_onconnectstatechange(void* feature, AppendData append_data)
{
    return g_feature_a2dp_sink_callbacks.a2dp_sink_connection_state_cbs[feature];
}
void system_bluetooth_bt_a2dpsink_set_onconnectstatechange(void* feature, AppendData append_data, FtCallbackId onconnectstatechange)
{
    g_feature_a2dp_sink_callbacks.a2dp_sink_connection_state_cbs[feature] = onconnectstatechange;
}

void a2dp_sink_feature_init(void* handle)
{
    sink_cbks_cookie = bt_a2dp_sink_register_callbacks(reinterpret_cast<bt_instance_t*>(handle), &a2dp_sink_cbs);

}

void a2dp_sink_feature_uninit(void* handle)
{
    bt_a2dp_sink_unregister_callbacks(reinterpret_cast<bt_instance_t*>(handle), sink_cbks_cookie);
}
