/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#include "system_bluetooth_bt_a2dpsink.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_main_exports.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

/****** for JIDL struct 'OnConnectStateChangeData' ******/
static ObjectMember system_bluetooth_bt_a2dpsink_OnConnectStateChangeData_struct_members[] = {
    { "deviceId", FT_STRING, offsetof(system_bluetooth_bt_a2dpsink_OnConnectStateChangeData, deviceId), sizeof(FtString) },
    { "connectState", FT_INT, offsetof(system_bluetooth_bt_a2dpsink_OnConnectStateChangeData, connectState), sizeof(FtInt) },
    { NULL },
};

// complex defination
static const ObjectMapType system_bluetooth_bt_a2dpsink_OnConnectStateChangeData_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_bluetooth_bt_a2dpsink_OnConnectStateChangeData) },
    .members = system_bluetooth_bt_a2dpsink_OnConnectStateChangeData_struct_members
};

system_bluetooth_bt_a2dpsink_OnConnectStateChangeData* system_bluetooth_bt_a2dpsinkMallocOnConnectStateChangeData () {
    return (system_bluetooth_bt_a2dpsink_OnConnectStateChangeData*)FeatureMalloc(
        sizeof(system_bluetooth_bt_a2dpsink_OnConnectStateChangeData), FT_MK_COMPLEX_REF(&system_bluetooth_bt_a2dpsink_OnConnectStateChangeData_struct_type));
}


/****** for JIDL callback 'onConnectStateChangeCallback' ******/
static const FeatureType system_bluetooth_bt_a2dpsink_onConnectStateChangeCallback_parameters[] = {
    FT_MK_COMPLEX(&system_bluetooth_bt_a2dpsink_OnConnectStateChangeData_struct_type),
    FT_PARAM_END
};

static const CallbackType system_bluetooth_bt_a2dpsink_onConnectStateChangeCallback_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_bluetooth_bt_a2dpsink_onConnectStateChangeCallback_parameters,
    .return_type = FT_VOID
};


/****** for JIDL property 'onconnectstatechange' ******/
static const MemberAccessor system_bluetooth_bt_a2dpsink_onconnectstatechange_member_accessor = {
    .getter = { .callback = FFI_FN(system_bluetooth_bt_a2dpsink_get_onconnectstatechange) },
    .setter = { .callback = FFI_FN(system_bluetooth_bt_a2dpsink_set_onconnectstatechange) },
    .type = FT_MK_COMPLEX(&system_bluetooth_bt_a2dpsink_onConnectStateChangeCallback_callback_type),
};


// members
static const Member system_bluetooth_bt_a2dpsink_members[] = {
    {
        .type = MEMBER_ACCESSOR,
        .name = "onconnectstatechange",
        .accessor = &system_bluetooth_bt_a2dpsink_onconnectstatechange_member_accessor,
    },
};

// callbacks
static const struct FeatureCallbacks system_bluetooth_bt_a2dpsink_callbacks = {
    system_bluetooth_bt_a2dpsink_onRegister,
    system_bluetooth_bt_a2dpsink_onCreate,
    system_bluetooth_bt_a2dpsink_onRequired,
    system_bluetooth_bt_a2dpsink_onDetached,
    system_bluetooth_bt_a2dpsink_onDestroy,
    system_bluetooth_bt_a2dpsink_onUnregister
};

static const FeatureDescription system_bluetooth_bt_a2dpsink_desc = {
    .version = 1,
    .name = "system.bluetooth.bt.a2dpsink",
    .description = "system.bluetooth.bt.a2dpsink",
    { .dynamic = false },
    .native_callbacks = &system_bluetooth_bt_a2dpsink_callbacks,
    .member_count = countof(system_bluetooth_bt_a2dpsink_members),
    .members = system_bluetooth_bt_a2dpsink_members,
};

QAPPFEATURE_INIT(system_bluetooth_bt_a2dpsink)
{
    FEATURE_LOG_ERROR("a2dp sink res =========================================================()\n");
    return FeatureRegisterFeature(handle, &system_bluetooth_bt_a2dpsink_desc);
}
/* clang-format on */
