/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#include <string>
#include "bluetooth.h"
#include "bt_a2dp_sink.h"
#include "feature_bluetooth_constant.h"
#include "feature_adapter.h"
#include "system_bluetooth_bt.h"


#define file_tag "system_bluetooth_bt"
// FeatureCallbacks to be implemented
static bt_status_t bluetooth_connect_profiles(bt_addr* addr, feature_profile_t profile_id)
{
    bt_status_t status = BT_STATUS_NOT_SUPPORTED;
    switch (profile_id) {
    case A2DP_SINK:
#ifdef CONFIG_BLUETOOTH_A2DP_SINK
        status = bt_a2dp_sink_connect(feature_bluetooth_get_instance(), addr);
#endif
        break;
    default:
        break;
    }
    return status;
}

static bt_status_t bluetooth_disconnect_profiles(bt_addr* addr, feature_profile_t profile_id)
{
    bt_status_t status = BT_STATUS_NOT_SUPPORTED;
    switch (profile_id) {
    case A2DP_SINK:
#ifdef CONFIG_BLUETOOTH_A2DP_SINK
        status = bt_a2dp_sink_disconnect(feature_bluetooth_get_instance(), addr);
#endif
        break;
    default:
        break;
    }
    return status;
}

static char* StringToFtString(std::string str)
{
    int len = str.length();
    char* ftStr = (char*)FeatureMalloc(len + 1, FT_CHAR);
    strcpy(ftStr, str.c_str());
    return ftStr;
}

void system_bluetooth_bt_onRegister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle)
{
    clean_feature_adapter_callback(handle);
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_onUnregister(const char* feature_name)
{
    FEATURE_LOG_INFO("%s::%s()\n", file_tag, __FUNCTION__);
}

void system_bluetooth_bt_wrap_startDiscovery(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_StartDiscoveryParams* params)
{
    int timeout = 120;
    bt_status_t status = bt_adapter_start_discovery(feature_bluetooth_get_instance(), timeout);
    if (status == BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke start discovery success  failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_fail, "start discovery failed!", status)) {
            FEATURE_LOG_ERROR("invoke start discovery fail callback failed!");
            return;
        }
    }
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke start discovery complete callback failed!");
        return;
    }
}
void system_bluetooth_bt_wrap_stopDiscovery(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_StopDiscoveryParams* params)
{
    bt_status_t status = bt_adapter_cancel_discovery(feature_bluetooth_get_instance());
    if (status == BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke stop discovery success callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_fail, "stop discovery failed!", status)) {
            FEATURE_LOG_ERROR("invoke stop discovery fail callback failed!");
            return;
        }
    }
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke stop discovery complete callback failed!");
        return;
    }
}

void system_bluetooth_bt_wrap_connectProfiles(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_ConnectProfilesParams* params)
{
    int profiles_num = params->_profiles->_size;
    int* profiles = reinterpret_cast<int*>(params->_profiles->_element);
    bt_address_t addr;
    int status = BT_STATUS_SUCCESS;
    if (bt_addr_str2ba(params->_deviceId, &addr) < 0) {
        if (!FeatureInvokeCallback(feature, params->_fail, "invalid addr!", BT_STATUS_PARM_INVALID)) {
            FEATURE_LOG_ERROR("invoke connect profiles fail callback failed!");
            return;
        }
        goto COMPLETE_CALLBACK;
    }

    for (int i = 0; i < profiles_num; ++i) {
        status |= bluetooth_connect_profiles(&addr, static_cast<feature_profile_t>(profiles[i]));
    }

    if (status != BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_fail, "connect all passing profiles failed!", status)) {
            FEATURE_LOG_ERROR("invoke connect profiles fail callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke connect profiles success callback failed!");
            return;
        }
    }
COMPLETE_CALLBACK:
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke connect profiles complete callback failed!");
        return;
    }
}

void system_bluetooth_bt_wrap_disconnectProfiles(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_DisconnectProfilesParams* params)
{
    int profiles_num = params->_profiles->_size;
    int* profiles = reinterpret_cast<int*>(params->_profiles->_element);
    bt_address_t addr;
    int status = BT_STATUS_SUCCESS;
    if (bt_addr_str2ba(params->_deviceId, &addr) < 0) {
        if (!FeatureInvokeCallback(feature, params->_fail, "invalid addr!", BT_STATUS_PARM_INVALID)) {
            FEATURE_LOG_ERROR("invoke disconnect profiles fail callback failed!");
            return;
        }
        goto COMPLETE_CALLBACK;
    }
    for (int i = 0; i < profiles_num; ++i) {
        status |= bluetooth_disconnect_profiles(&addr, static_cast<feature_profile_t>(profiles[i]));
    }
    if (status != BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_fail, "disconnect all passing profiles failed!", status)) {
            FEATURE_LOG_ERROR("invoke disconnect profiles fail callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke disconnect profiles success callback failed!");
            return;
        }
    }
COMPLETE_CALLBACK:
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke disconnect profiles complete callback failed!");
        return;
    }
}

void system_bluetooth_bt_wrap_disconnect(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_DisconnectParams* params)
{
    bt_address_t addr;
    bt_status_t status;
    if (bt_addr_str2ba(params->_deviceId, &addr) < 0) {
        if (!FeatureInvokeCallback(feature, params->_fail, "invalid addr!", BT_STATUS_PARM_INVALID)) {
            FEATURE_LOG_ERROR("invoke disconnect fail callback failed!");
            return;
        }
        goto COMPLETE_CALLBACK;
    }
    status = bt_device_disconnect(feature_bluetooth_get_instance(), &addr);
    if (status != BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_fail, "disconnect failed!", status)) {
            FEATURE_LOG_ERROR("invoke disconnect fail callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke disconnect success callback failed!");
            return;
        }
    }
COMPLETE_CALLBACK:
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke disconnect complete callback failed!");
        return;
    }
}

FtBool system_bluetooth_bt_wrap_getConnectState(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId)
{
    FtBool connected = false;
    bt_address_t addr;
    if (bt_addr_str2ba(deviceId, &addr) < 0) {
        return false;
    }
#ifdef CONFIG_BLUETOOTH_A2DP_SINK
    connected |= bt_a2dp_sink_get_connection_state(feature_bluetooth_get_instance(), &addr);
#endif
    return connected;
}

FtArray* system_bluetooth_bt_wrap_getConnectedDevices(FeatureInstanceHandle feature, AppendData append_data)
{
    bt_address_t* addrs = nullptr;
    int num = 0;
    bt_adapter_get_connected_devices(feature_bluetooth_get_instance(), BT_TRANSPORT_BREDR, &addrs, &num, bt_feature_allocator);
    FtArray* devices = system_bluetooth_bt_malloc_string_array();
    devices->_size = num;
    devices->_element = FeatureMalloc(devices->_size, FT_STRING);
    for (int i = 0; i < devices->_size; ++i) {
        char addr_str[BT_ADDR_STR_LENGTH] = { 0 };
        bt_addr_ba2str(addrs + i, addr_str);
        ((char**)devices->_element)[i] = StringToFtString(addr_str);
    }
    free(addrs);
    return devices;
}

FtArray* system_bluetooth_bt_wrap_getBondedDevices(FeatureInstanceHandle feature, AppendData append_data)
{
    bt_address_t* addrs = nullptr;
    int num = 0;
    bt_adapter_get_bonded_devices(feature_bluetooth_get_instance(), BT_TRANSPORT_BREDR, &addrs, &num, bt_feature_allocator);
    FtArray* devices = system_bluetooth_bt_malloc_string_array();
    devices->_size = num;
    devices->_element = FeatureMalloc(devices->_size, FT_STRING);
    for (int i = 0; i < devices->_size; ++i) {
        char addr_str[BT_ADDR_STR_LENGTH] = { 0 };
        bt_addr_ba2str(addrs + i, addr_str);
        ((char**)devices->_element)[i] = StringToFtString(addr_str);
    }
    free(addrs);
    return devices;
}

void system_bluetooth_bt_wrap_removeBondedDevice(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_RemoveBondedParams* params)
{
    bt_address_t addr;
    bt_status_t status;
    if (bt_addr_str2ba(params->_deviceId, &addr) < 0) {
        if (!FeatureInvokeCallback(feature, params->_fail, "invalid addr!", BT_STATUS_PARM_INVALID)) {
            FEATURE_LOG_ERROR("invoke remove bonded fail callback failed!");
            return;
        }
        goto COMPLETE_CALLBACK;
    }
    status = bt_device_remove_bond(feature_bluetooth_get_instance(), &addr, BT_TRANSPORT_BREDR);
    if (status != BT_STATUS_SUCCESS) {
        if (!FeatureInvokeCallback(feature, params->_fail, "remove bonded failed!", status)) {
            FEATURE_LOG_ERROR("invoke remove bonded fail callback failed!");
            return;
        }
    } else {
        if (!FeatureInvokeCallback(feature, params->_success)) {
            FEATURE_LOG_ERROR("invoke remove bonded success callback failed!");
            return;
        }
    }
COMPLETE_CALLBACK:
    if (!FeatureInvokeCallback(feature, params->_complete)) {
        FEATURE_LOG_ERROR("invoke remove bonded complete callback failed!");
        return;
    }
}

FtBool system_bluetooth_bt_wrap_setScanMode(FeatureInstanceHandle feature, AppendData append_data, FtInt scanMode)
{
    if (bt_adapter_set_scan_mode(feature_bluetooth_get_instance(), static_cast<bt_scan_mode_t>(scanMode), 1) == BT_STATUS_SUCCESS) {
        return true;
    } else {
        return false;
    }
}

FtInt system_bluetooth_bt_wrap_getScanMode(FeatureInstanceHandle feature, AppendData append_data)
{
    return bt_adapter_get_scan_mode(feature_bluetooth_get_instance());
}

FtString system_bluetooth_bt_wrap_getDeviceName(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId)
{
    bt_address_t addr;
    char name[64] = { 0 };
    if (bt_addr_str2ba(deviceId, &addr) < 0) {
        return StringToFtString("");
    }
    bt_device_get_name(feature_bluetooth_get_instance(), &addr, name, 64);
    return StringToFtString(name);
}

unsigned int system_bluetooth_bt_wrap_getDeviceClass(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId)
{
    bt_address_t addr;
    if (bt_addr_str2ba(deviceId, &addr) < 0) {
        return 0;
    }

    return bt_device_get_device_class(feature_bluetooth_get_instance(), &addr);
}

FtCallbackId system_bluetooth_bt_get_discoveryresult(void* feature, AppendData append_data)
{
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    return adaptercallbacks->on_discovery_result_cbs[feature];
}

void system_bluetooth_bt_set_discoveryresult(void* feature, AppendData append_data, FtCallbackId discoveryresult)
{
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    adaptercallbacks->on_discovery_result_cbs[feature] = discoveryresult;
}

FtCallbackId system_bluetooth_bt_get_onbondstatechange(void* feature, AppendData append_data)
{
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    return adaptercallbacks->on_discovery_result_cbs[feature];
}

void system_bluetooth_bt_set_onbondstatechange(void* feature, AppendData append_data, FtCallbackId onbondstatechange)
{
    adapter_feature_callbacks_t* adaptercallbacks = get_adapter_cbs();
    adaptercallbacks->on_bond_state_changed_cbs[feature] = onbondstatechange;
}
