

#ifndef _SRV_INC_GATT_BT_COMOM_H
#define _SRV_INC_GATT_BT_COMOM_H

#include <stdbool.h>
#include <stdint.h>

#include "stack_adapter_common.h"
#include "stack_adapter_gatt.h"

typedef SERVICE_BLE_KEYS_S ble_keys_t;
typedef SERVICE_LE_CONNECT_PARAMS_S ble_connect_params_t;
typedef SERVICE_SSP_REPLY_DATA_S spp_reply_data_t;
typedef SERVICE_BT_TEST_MODE bt_test_mode;

typedef SERVICE_SCAN_PARAMS_S scan_params_t;
typedef SERVICE_BLE_SCAN_FILTER_S ble_scan_filter_t;
typedef SERVICE_SCAN_RESULT_DATA_S scan_result_t;
typedef BD_ADDR bd_addr_t;
typedef BT_UUID_T bt_uuid_t;

typedef SERVICE_PROFILE_CONNECTION_STATE profile_state_t;
typedef SERVICE_SCAN_ADV_PARAMS_S advertise_param_t;
typedef SERVICE_GATT_ELEMENT_S gatt_element_t;
typedef SERVICE_GATT_RESPONSE_S gatt_response_t;

typedef SERVICE_GATT_STATUS gatt_status_t;
typedef SERVICE_BLE_PHY_TYPE ble_phy_type_t;
typedef SERVICE_BT_STACK_STATE stack_state_t;
typedef GATT_SERVER_CALLBACKS_S stack_gatt_server_callbacks;
typedef GATT_CLIENT_CALLBACKS_S stack_gatt_client_callbacks;
typedef SERVICE_PIN_REQUEST_DATA_S pin_request_data_t;
typedef SERVICE_BT_DISCOVERY_STATE discovery_state;

typedef SERVICE_SSP_REQUEST_DATA_S ssp_request_data_t;
typedef SERVICE_BT_BOND_STATE bt_bonde_state;
typedef SERVICE_ACL_STATE_PARAM_S acl_state_params_t;
typedef SERVICE_BT_LINK_ROLE bt_link_role;
typedef SERVICE_BT_SCAN_MODE bt_scan_mode;
typedef SERVICE_BT_LINK_MODE bt_link_mode;
typedef SERVICE_BT_LINK_POLICY bt_link_policy;
typedef SERVICE_BT_HCI_EVENT_S hci_event_t;
typedef SERVICE_REMOTE_DEVICE_S remote_device_t;
typedef SERVICE_BR_SERVICE_S br_service_t;
typedef SERVICE_BT_STATUS bt_status;
typedef SERVICE_BLE_ADDR_TYPE ble_addr_type;
typedef BT_COMMON_KEY bt_common_key;
#endif