/****************************************************************************
 *  Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#ifndef __SAL_LE_CS_INTERFACE_H__
#define __SAL_LE_CS_INTERFACE_H__

#include "bluetooth.h"
#include "cs_service.h"
#include <stdint.h>

typedef struct {
    struct {
        /** CS configuration identifier.
         *
         *  Range: 0 to 3
         *
         *  If these results were generated by a CS Test,
         *  this value should be set to 0 and has no meaning.
         */
        uint8_t config_id;
        /** Starting ACL connection event counter.
         *
         *  If these results were generated by a CS Test,
         *  this value should be set to 0 and has no meaning.
         */
        uint16_t start_acl_conn_event_counter;
        /** CS procedure count associated with these results.
         *
         *  This is the CS procedure count since the completion of
         *  the Channel Sounding Security Start procedure.
         */
        uint16_t procedure_counter;
        /** Frequency compensation value in units of 0.01 ppm.
         *
         *  This is a 15-bit signed integer in the range [-100, 100] ppm.
         *
         *  0xC000 indicates that the role is not the initiator, or that the
         *  frequency compensation value is unavailable.
         */
        uint16_t frequency_compensation;
        /** Reference power level in dBm.
         *
         *  Range: -127 to 20
         *
         *  0x7F indicates that the reference power level was not available during a subevent.
         */
        int8_t reference_power_level;
        /** Procedure done status. */
        bt_le_srv_cs_procedure_done_status_t procedure_done_status;
        /** Subevent status
         *
         *  For aborted subevents,
         *  and abort_step will contain the step number on which the subevent was aborted.
         *  Consider the following example:
         *
         *  subevent_done_status = @ref SAL_LE_CS_SUBEVENT_ABORTED
         *  num_steps_reported = 160
         *  abort_step = 100
         *
         *  this would mean that steps from 0 to 99 are complete and steps from 100 to 159
         *  are aborted.
         */
        bt_le_srv_le_cs_subevent_done_status_t subevent_done_status;
        /** Abort reason.
         *
         *  If the procedure status is
         *  @ref SAL_LE_CS_PROCEDURE_ABORTED, this field will
         *  specify the reason for the abortion.
         */
        bt_le_srv_cs_procedure_abort_reason_t procedure_abort_reason;
        /** Abort reason.
         *
         *  If the subevent status is
         *  @ref SAL_LE_CS_SUBEVENT_ABORTED, this field will
         *  specify the reason for the abortion.
         */
        bt_le_srv_cs_subevent_abort_reason_t subevent_abort_reason;
        /** Number of antenna paths used during the phase measurement stage.
         */
        uint8_t num_antenna_paths;
        /** Number of CS steps in the subevent.
         */
        uint8_t num_steps_reported;
        /** Step number, on which the subevent was aborted
         *  if subevent_done_status is @ref SAL_LE_CS_SUBEVENT_COMPLETE
         *  then abort_step will be unused and set to 255
         */
        uint8_t abort_step;
    } header;

    uint16_t len;
    uint8_t* step_data_buf;
} sal_cs_subevent_result_t;

bt_status_t bt_sal_cs_read_remote_supported_capabilities(bt_controller_id_t id, bt_address_t* addr);
bt_status_t bt_sal_cs_set_default_settings(bt_controller_id_t id, bt_address_t* addr,
    bt_le_srv_cs_set_default_settings_param_t* params);
bt_status_t bt_sal_cs_read_remote_fae_table(bt_controller_id_t id, bt_address_t* addr);
bt_status_t bt_sal_cs_create_config(bt_controller_id_t id, bt_address_t* addr,
    bt_le_srv_cs_create_config_params_t* params,
    bt_le_srv_cs_create_config_context_t context);
bt_status_t bt_sal_cs_security_enable(bt_controller_id_t id, bt_address_t* addr);
bt_status_t bt_sal_cs_procedure_enable(bt_controller_id_t id, bt_address_t* addr, const bt_le_srv_cs_procedure_enable_param_t* params);
bt_status_t bt_sal_cs_remove_config(bt_controller_id_t id, bt_address_t* addr, uint8_t config_id);
bt_status_t bt_sal_cs_set_procedure_parameters(bt_controller_id_t id, bt_address_t* addr,
    const bt_le_srv_cs_set_procedure_parameters_param_t* params);
bt_status_t bt_sal_cs_set_channel_classification(bt_controller_id_t id, uint8_t channel_classification[10], bt_address_t* addr);
bt_status_t bt_sal_cs_read_local_supported_capabilities(bt_controller_id_t id, bt_srv_conn_le_cs_capabilities_t* params, bt_address_t* addr);
bt_status_t bt_sal_cs_write_cached_remote_supported_capabilities(bt_controller_id_t id, const bt_srv_conn_le_cs_capabilities_t* params,
    bt_address_t* addr);

#endif //__SAL_LE_CS_INTERFACE_H__