/****************************************************************************
 *  Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#ifndef _CS_RAS_CLIENT_H_
#include <zephyr/bluetooth/conn.h>
#include <zephyr/bluetooth/gatt.h>

// Maximum number of segments (derived from Segment Index range in Segmentation Header)
#define MAX_SEGMENTS 64
#define MAX_SUBEVENT_RESULT    10

#define SAL_LE_RAP_STEP_DATA_BUF_LEN 2048

typedef struct {
    /** CS configuration identifier.
     *
     *  Range: 0 to 3
     *
     *  If these results were generated by a CS Test,
     *  this value will be set to 0 and has no meaning.
     */
    uint8_t config_id;
    /** Starting ACL connection event counter.
     *
     *  If these results were generated by a CS Test,
     *  this value will be set to 0 and has no meaning.
     */
    uint16_t start_acl_conn_event;
    /** CS procedure count associated with these results.
     *
     *  This is the CS procedure count since the completion of
     *  the Channel Sounding Security Start procedure.
     */
    uint16_t procedure_counter;
    /** Frequency compensation value in units of 0.01 ppm.
     *
     *  This is a 15-bit signed integer in the range [-100, 100] ppm.
     *
     *  A value of @ref BT_HCI_LE_CS_SUBEVENT_RESULT_FREQ_COMPENSATION_NOT_AVAILABLE
     *  indicates that the role is not the initiator, or that the
     *  frequency compensation value is unavailable.
     */
    uint16_t frequency_compensation;
    /** Reference power level in dBm.
     *
     *  Range: -127 to 20
     *
     *  A value of @ref BT_HCI_LE_CS_REF_POWER_LEVEL_UNAVAILABLE indicates
     *  that the reference power level was not available during a subevent.
     */
    int8_t reference_power_level;
    /** Procedure status. */
    enum bt_conn_le_cs_procedure_done_status procedure_done_status;
    /** Subevent status
     *
     *  For aborted subevents, this will be set to @ref BT_CONN_LE_CS_SUBEVENT_ABORTED
     *  and abort_step will contain the step number on which the subevent was aborted.
     *  Consider the following example:
     *
     *  subevent_done_status = @ref BT_CONN_LE_CS_SUBEVENT_ABORTED
     *  num_steps_reported = 160
     *  abort_step = 100
     *
     *  this would mean that steps from 0 to 99 are complete and steps from 100 to 159
     *  are aborted.
     */
    enum bt_conn_le_cs_subevent_done_status subevent_done_status;
    /** Abort reason.
     *
     *  If the procedure status is
     *  @ref BT_CONN_LE_CS_PROCEDURE_ABORTED, this field will
     *  specify the reason for the abortion.
     */
    enum bt_conn_le_cs_procedure_abort_reason procedure_abort_reason;
    /** Abort reason.
     *
     *  If the subevent status is
     *  @ref BT_CONN_LE_CS_SUBEVENT_ABORTED, this field will
     *  specify the reason for the abortion.
     */
    enum bt_conn_le_cs_subevent_abort_reason subevent_abort_reason;
    /** Number of antenna paths used during the phase measurement stage.
     */
    uint8_t num_antenna_paths;
    /** Number of CS steps in the subevent.
     */
    uint8_t num_steps_reported;
    /** Step number, on which the subevent was aborted
     *  if subevent_done_status is @ref BT_CONN_LE_CS_SUBEVENT_COMPLETE
     *  then abort_step will be unused and set to 255
     */
    uint8_t abort_step;
} rap_subevent_header_t;

// Define the segmentation header structure with rap_ prefix
typedef struct {
    unsigned char first_segment : 1;  // Flag indicating if it's the first segment
    unsigned char last_segment : 1;   // Flag indicating if it's the last segment
    unsigned char segment_index : 6;  // Segment index (0-63)
} rap_segmentation_header_t;

// Define the structure for the received data segment with rap_ prefix
typedef struct {
    rap_segmentation_header_t header;  // Segmentation header
    uint8_t *data;                     // The data content
    size_t data_size;                  // The size of the data
} rap_ranging_data_segment_t;

// Define the complete Ranging Data structure with rap_ prefix
typedef struct {
    uint8_t *data;         // The complete data
    size_t total_size;     // The total size of the data
    size_t received_size;  // The size of data received so far
    bool *segment_received; // Flag for each segment, indicating if it's been received
} rap_ranging_data_body_t;

enum ras_svc_disc_state_bit {
	DISC_RAS_RANG_RT_DT,
	DISC_RAS_NAME,
	DISC_RAS_TYPE,
	DISC_RAS_SIZE,
	DISC_RAS_ID,
};

typedef struct {
	uint16_t rang_realtime_data_handle;
	uint16_t rang_feature_handle;
	uint16_t rang_on_demond_data_handle;
	uint16_t rang_ras_ctr_point_handle;
	uint16_t rang_data_ready_handle;
	uint16_t rang_data_ov_wr_handle;
    uint16_t step_data_attr_handle;
} ras_char_handle_t;

typedef struct {
    rap_subevent_header_t header;
    bool is_used;
    uint8_t *local_steps;
} rap_subevent_result_t;

typedef struct {
	ras_char_handle_t char_handles;
    struct bt_conn *connection;
    uint32_t ras_mtu;
    uint32_t ras_seg_offset;
    uint32_t remaining_len;
    uint8_t ras_seg_idx;
    uint32_t feature;
    rap_subevent_result_t result_pool[MAX_SUBEVENT_RESULT];
    struct bt_gatt_indicate_params ras_dt_rd_ind_params;
    struct bt_gatt_read_params read_feature;
    uint32_t ras_feature;
    atomic_t disc_state;
	uint8_t *ras_svc_data;
	uint8_t *ras_cli_data;
} sal_le_ras_cli_env_t;

#endif /* _CS_RAS_CLIENT_H_ */