/****************************************************************************
 *  Copyright (C) 2026 Xiaomi Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/

#include <nuttx/config.h>

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <setjmp.h>
#include <cmocka.h>

#include "cm_bluetooth.h"
#include "cm_bt_a2dp_sink.h"
#include "cm_bt_a2dp_source.h"
#include "cm_bt_adapter.h"
#include "cm_bt_avrcp_control.h"
#include "cm_bt_avrcp_target.h"
#include "cm_bt_device.h"
#include "cm_bt_gattc.h"
#include "cm_bt_gatts.h"
#include "cm_bt_hfp_ag.h"
#include "cm_bt_hfp_hf.h"
#include "cm_bt_hid_device.h"
#include "cm_bt_l2cap.h"
#include "cm_bt_le_advertiser.h"
#include "cm_bt_le_scan.h"
#include "cm_bt_pan.h"
#include "cm_bt_spp.h"

int cmocka_framework_api_test_main(int argc, FAR char* argv[])
{
    const struct CMUnitTest framework_api_tests[] = {
        /* bt_adapter tests (60) */

        cmocka_unit_test_setup_teardown(test_bt_adapter_register_callback_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_register_callback_null_cbs,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_unregister_callback_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_unregister_callback_null_cookie,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_enable_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_enable_fail,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_disable_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_disable_fail,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_disable_safe_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_enable_le_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_disable_le_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_state_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_state_disabled,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_le_enabled_true,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_le_enabled_false,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_type_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_discovery_filter_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_start_discovery_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_start_discovery_fail,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_start_discovery_zero_timeout,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_start_limited_discovery_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_cancel_discovery_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_cancel_discovery_fail,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_discovering_true,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_discovering_false,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_address_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_name_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_name_null,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_name_empty,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_name_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_uuids_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_scan_mode_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_scan_mode_fail,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_scan_mode_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_device_class_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_device_class_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_io_capability_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_io_capability_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_inquiry_scan_params_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_page_scan_params_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_le_io_capability_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_le_io_capability_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_le_address_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_le_address_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_le_identity_address_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_le_appearance_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_le_appearance_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_le_enable_key_derivation_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_le_add_whitelist_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_le_add_whitelist_with_type_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_le_remove_whitelist_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_bonded_devices_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_get_connected_devices_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_afh_channel_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_disconnect_all_devices_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_bredr_true,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_bredr_false,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_le_true,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_le_false,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_leaudio_true,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_is_support_leaudio_false,
            test_bt_adapter_setup, test_bt_adapter_teardown),
        cmocka_unit_test_setup_teardown(test_bt_adapter_set_debug_mode_normal,
            test_bt_adapter_setup, test_bt_adapter_teardown),

        /* bt_device tests (70) */

        cmocka_unit_test_setup_teardown(test_bt_device_get_identity_address_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_identity_address_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_address_type_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_address_type_unknown,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_device_type_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_device_type_not_found,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_name_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_name_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_device_class_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_device_class_not_found,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_uuids_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_uuids_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_appearance_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_appearance_zero,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_rssi_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_rssi_zero,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_alias_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_alias_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_alias_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_alias_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_connected_true,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_connected_false,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_encrypted_true,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_encrypted_false,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_bond_initiate_local_true,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_bond_initiate_local_false,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_bond_state_bonded,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_bond_state_none,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_bonded_true,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_is_bonded_false,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disconnect_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disconnect_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_le_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_le_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disconnect_le_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disconnect_le_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_request_reply_accept,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_request_reply_reject,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_connect_all_profile_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disconnect_all_profile_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_phy_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_phy_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_create_bond_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_create_bond_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_security_level_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_security_level_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_bondable_le_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_bondable_le_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_remove_bond_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_remove_bond_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_cancel_bond_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_cancel_bond_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_pair_request_reply_accept,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_pair_request_reply_reject,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pairing_confirmation_accept,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pairing_confirmation_reject,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pin_code_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pin_code_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pass_key_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_pass_key_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_legacy_tk_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_legacy_tk_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_sc_remote_oob_data_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_set_le_sc_remote_oob_data_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_le_sc_local_oob_data_normal,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_get_le_sc_local_oob_data_fail,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_enable_enhanced_mode_unsupported,
            test_bt_device_setup, test_bt_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_device_disable_enhanced_mode_unsupported,
            test_bt_device_setup, test_bt_device_teardown),

        /* bt_le_scan tests (15) */

        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_normal,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_fail,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_null_cbs,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_settings_normal,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_settings_fail,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_settings_null_settings,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_with_filters_normal,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_with_filters_fail,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_with_filters_null_filter,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_scan_normal,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_scan_null_scanner,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_scan_is_supported_true,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_scan_is_supported_false,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_returns_valid_scanner,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_scan_settings_returns_valid_scanner,
            test_bt_le_scan_setup, test_bt_le_scan_teardown),

        /* bt_gattc tests (36) */

        cmocka_unit_test_setup_teardown(test_bt_gattc_create_connect_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_create_connect_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_delete_connect_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_delete_connect_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_connect_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_connect_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_disconnect_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_disconnect_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_discover_service_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_discover_service_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_get_attribute_by_handle_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_get_attribute_by_handle_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_get_attribute_by_uuid_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_get_attribute_by_uuid_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_without_response_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_without_response_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_with_signed_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_write_with_signed_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_subscribe_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_subscribe_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_unsubscribe_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_unsubscribe_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_exchange_mtu_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_exchange_mtu_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_update_connection_parameter_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_update_connection_parameter_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_phy_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_phy_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_update_phy_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_update_phy_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_rssi_normal,
            test_bt_gattc_setup, test_bt_gattc_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gattc_read_rssi_fail,
            test_bt_gattc_setup, test_bt_gattc_teardown),

        /* bluetooth tests (20) */

        cmocka_unit_test_setup_teardown(test_bluetooth_create_instance_normal,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_create_instance_alloc_fail,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_create_instance_manager_fail,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_instance_existing,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_instance_new,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_proxy_hfp_hf,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_proxy_default,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_delete_instance_normal,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_start_service_normal,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_start_service_fail,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_stop_service_normal,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_stop_service_fail,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_create_instance_sets_app_id,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_instance_returns_existing,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_proxy_null_proxy,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_start_service_invalid_profile,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_stop_service_invalid_profile,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_delete_instance_frees_memory,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_create_instance_getpid_called,
            test_bluetooth_setup, test_bluetooth_teardown),
        cmocka_unit_test_setup_teardown(test_bluetooth_get_instance_getpid_called,
            test_bluetooth_setup, test_bluetooth_teardown),

        /* bt_le_advertiser tests (12) */

        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_normal,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_fail,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_null_params,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_null_adv_data,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_null_scan_rsp,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_start_advertising_returns_valid,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_advertising_normal,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_advertising_null_adver,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_advertising_id_normal,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_stop_advertising_id_zero,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_advertising_is_supported_true,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),
        cmocka_unit_test_setup_teardown(test_bt_le_advertising_is_supported_false,
            test_bt_le_advertiser_setup, test_bt_le_advertiser_teardown),

        /* bt_gatts tests (28) */

        cmocka_unit_test_setup_teardown(test_bt_gatts_register_service_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_register_service_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_unregister_service_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_unregister_service_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_connect_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_connect_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_connect_bear_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_connect_bear_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_disconnect_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_disconnect_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_add_attr_table_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_add_attr_table_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_remove_attr_table_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_remove_attr_table_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_set_attr_value_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_set_attr_value_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_get_attr_value_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_get_attr_value_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_response_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_response_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_notify_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_notify_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_indicate_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_indicate_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_read_phy_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_read_phy_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_update_phy_normal,
            test_bt_gatts_setup, test_bt_gatts_teardown),
        cmocka_unit_test_setup_teardown(test_bt_gatts_update_phy_fail,
            test_bt_gatts_setup, test_bt_gatts_teardown),

        /* bt_a2dp_sink tests (16) */

        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_register_callbacks_normal,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_register_callbacks_fail,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_unregister_callbacks_normal,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_unregister_callbacks_fail,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_is_connected_true,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_is_connected_false,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_is_playing_true,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_is_playing_false,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_get_connection_state_connected,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_get_connection_state_disconnected,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_connect_normal,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_connect_fail,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_disconnect_normal,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_disconnect_fail,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_set_active_device_normal,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_sink_set_active_device_fail,
            test_bt_a2dp_sink_setup, test_bt_a2dp_sink_teardown),

        /* bt_a2dp_source tests (18) */

        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_register_callbacks_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_register_callbacks_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_unregister_callbacks_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_unregister_callbacks_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_is_connected_true,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_is_connected_false,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_is_playing_true,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_is_playing_false,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_get_connection_state_connected,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_get_connection_state_disconnected,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_connect_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_connect_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_disconnect_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_disconnect_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_set_silence_device_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_set_silence_device_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_set_active_device_normal,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),
        cmocka_unit_test_setup_teardown(test_bt_a2dp_source_set_active_device_fail,
            test_bt_a2dp_source_setup, test_bt_a2dp_source_teardown),

        /* bt_hfp_hf tests (37) */

        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_register_callbacks_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_register_callbacks_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_unregister_callbacks_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_unregister_callbacks_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_is_connected_true,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_is_connected_false,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_is_audio_connected_true,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_is_audio_connected_false,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_get_connection_state_connected,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_get_connection_state_disconnected,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_connect_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_connect_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_disconnect_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_disconnect_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_set_connection_policy_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_set_connection_policy_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_connect_audio_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_connect_audio_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_disconnect_audio_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_disconnect_audio_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_start_voice_recognition_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_start_voice_recognition_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_stop_voice_recognition_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_stop_voice_recognition_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_dial_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_dial_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_dial_memory_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_dial_memory_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_redial_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_redial_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_accept_call_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_reject_call_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_hold_call_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_terminate_call_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_send_dtmf_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_volume_control_normal,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_hf_volume_control_fail,
            test_bt_hfp_hf_setup, test_bt_hfp_hf_teardown),

        /* bt_hfp_ag tests (28) */

        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_register_callbacks_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_register_callbacks_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_unregister_callbacks_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_unregister_callbacks_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_is_connected_true,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_is_connected_false,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_is_audio_connected_true,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_is_audio_connected_false,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_get_connection_state_connected,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_get_connection_state_disconnected,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_connect_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_connect_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_disconnect_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_disconnect_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_connect_audio_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_connect_audio_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_disconnect_audio_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_disconnect_audio_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_start_virtual_call_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_start_virtual_call_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_stop_virtual_call_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_stop_virtual_call_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_start_voice_recognition_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_start_voice_recognition_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_stop_voice_recognition_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_stop_voice_recognition_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_volume_control_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_volume_control_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_send_at_command_normal,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hfp_ag_send_at_command_fail,
            test_bt_hfp_ag_setup, test_bt_hfp_ag_teardown),

        /* bt_avrcp_control tests (16) */

        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_register_callbacks_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_register_callbacks_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_unregister_callbacks_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_unregister_callbacks_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_element_attributes_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_element_attributes_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_send_passthrough_cmd_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_send_passthrough_cmd_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_unit_info_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_unit_info_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_subunit_info_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_subunit_info_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_playback_state_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_get_playback_state_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_register_notification_normal,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_control_register_notification_fail,
            test_bt_avrcp_control_setup, test_bt_avrcp_control_teardown),

        /* bt_avrcp_target tests (12) */

        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_register_callbacks_normal,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_register_callbacks_fail,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_unregister_callbacks_normal,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_unregister_callbacks_fail,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_get_play_status_response_normal,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_get_play_status_response_fail,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_play_status_notify_normal,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_play_status_notify_fail,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_register_callbacks_null_cbs,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_unregister_callbacks_null_cookie,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_get_play_status_response_playing,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),
        cmocka_unit_test_setup_teardown(test_bt_avrcp_target_play_status_notify_paused,
            test_bt_avrcp_target_setup, test_bt_avrcp_target_teardown),

        /* bt_spp tests (16) */

        cmocka_unit_test_setup_teardown(test_bt_spp_register_app_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_register_app_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_register_app_with_name_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_register_app_with_name_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_unregister_app_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_unregister_app_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_server_start_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_server_start_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_server_stop_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_server_stop_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_connect_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_connect_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_insecure_connect_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_insecure_connect_fail,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_disconnect_normal,
            test_bt_spp_setup, test_bt_spp_teardown),
        cmocka_unit_test_setup_teardown(test_bt_spp_disconnect_fail,
            test_bt_spp_setup, test_bt_spp_teardown),

        /* bt_pan tests (10) */

        cmocka_unit_test_setup_teardown(test_bt_pan_register_callbacks_normal,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_register_callbacks_fail,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_unregister_callbacks_normal,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_unregister_callbacks_fail,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_connect_normal,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_connect_fail,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_disconnect_normal,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_disconnect_fail,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_connect_different_roles,
            test_bt_pan_setup, test_bt_pan_teardown),
        cmocka_unit_test_setup_teardown(test_bt_pan_register_callbacks_null_cbs,
            test_bt_pan_setup, test_bt_pan_teardown),

        /* bt_hid_device tests (20) */

        cmocka_unit_test_setup_teardown(test_bt_hid_device_register_callbacks_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_register_callbacks_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_unregister_callbacks_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_unregister_callbacks_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_register_app_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_register_app_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_unregister_app_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_unregister_app_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_connect_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_connect_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_disconnect_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_disconnect_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_send_report_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_send_report_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_response_report_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_response_report_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_report_error_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_report_error_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_virtual_unplug_normal,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),
        cmocka_unit_test_setup_teardown(test_bt_hid_device_virtual_unplug_fail,
            test_bt_hid_device_setup, test_bt_hid_device_teardown),

        /* bt_l2cap tests (15) */

        cmocka_unit_test_setup_teardown(test_bt_l2cap_register_callbacks_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_register_callbacks_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_unregister_callbacks_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_unregister_callbacks_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_listen_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_listen_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_connect_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_connect_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_disconnect_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_disconnect_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_stop_listen_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_stop_listen_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_stop_listen_with_transport_normal,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_stop_listen_with_transport_fail,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
        cmocka_unit_test_setup_teardown(test_bt_l2cap_register_callbacks_null_cbs,
            test_bt_l2cap_setup, test_bt_l2cap_teardown),
    };

    return cmocka_run_group_tests(framework_api_tests, NULL, NULL);
}
