/****************************************************************************
 *
 *   Copyright (C) 2021 Xiaomi InC. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/
#ifndef __BTM_SPP_H__
#define __BTM_SPP_H__

#include "btm_manager.h"

/* Unknow server channel number */
#define UNKNOWN_SERVER_CHANNEL_NUM -1

/* Serial Port Profile (SPP) UUID */
#define BT_UUID_SERVCLASS_SERIAL_PORT 0x1101

typedef enum {
    SPP_CONNECTION_STATE_DISCONNECTED,
    SPP_CONNECTION_STATE_CONNECTING,
    SPP_CONNECTION_STATE_CONNECTED,
    SPP_CONNECTION_STATE_DISCONNECTING
} spp_connection_state_t;

typedef enum {
    SPP_PTY_MODE_NORMAL,
    SPP_PTY_MODE_RAW
} spp_pty_mode_t;

typedef int (*spp_connection_state_callback)(const bt_address addr, uint16_t scn, uint16_t port, spp_connection_state_t state);
typedef void (*spp_pty_open_callback)(const bt_address addr, uint16_t port, char* name);

/* SPP event callbacks structure */
typedef struct {
    size_t size;
    spp_pty_open_callback pty_open_cb;
    spp_connection_state_callback connection_state_cb;
} spp_callbacks_t;

/* SPP interface structure */
typedef struct {
    size_t size;

    /**
     * @brief Start spp server
     * @param[in] handle    The spp application handle.
     * @param[in] scn       rfcomm server channel number, range in <1-28>.
     * @param[in] uuid16    sever class UUID.
     * @return BT_RESULT_SUCCESS on success; a negated errno value on failure.
     */
    bt_result_code (*server_start)(void* handle, uint16_t scn, uint16_t uuid16);

    /**
     * @brief Stop spp server
     * @param[in] handle    The spp application handle.
     * @param[in] scn       rfcomm server channel number, range in <1-28>.
     * @return BT_RESULT_SUCCESS on success; a negated errno value on failure.
     */
    bt_result_code (*server_stop)(void* handle, uint16_t scn);
    /**
     * @brief Connect to the spp server
     * @param[in] handle    The spp application handle.
     * @param[in] addr      address of peer device.
     * @param[in] scn       rfcomm server channel number, range in <1-28>.
     * @param[in] uuid16    sever class UUID.
     * @param[out] port     point to connection port.
     * @note port generated by spp service, each connection has a unique port.
     * @return BT_RESULT_SUCCESS on success; a negated errno value on failure.
     */
    bt_result_code (*client_connect)(void* handle, bt_address addr, int16_t scn, uint16_t uuid16, uint16_t *port);

    /**
     * @brief Connect to the spp server
     * @param[in] handle    The spp application handle.
     * @param[in] addr      address of peer device.
     * @param[in] port      unique port of connection.
     * @note If do not need to specify scn, use UNKNOWN_SERVER_CHANNEL_NUM
     * @return BT_RESULT_SUCCESS on success; a negated errno value on failure.
     */
    bt_result_code (*disconnect)(void* handle, bt_address addr, uint16_t port);

    /**
     * @brief Set the spp event callback
     * @note handle generated by spp service, each app has a unique handle.
     * @param[out] handle    The spp application handle.
     * @param[in] callbacks  spp event callback function.
     */
    void (*set_callbacks)(void** handle, spp_callbacks_t* callbacks);

    /**
     * @brief Reset the spp event callback
     * @param[in] handle    The spp application handle.
     */
    void (*reset_callbacks)(void** handle);
} spp_interface_t;

/**
 * @brief Get the spp interface
 * @return Pointer to spp interface.
 */
spp_interface_t* get_spp_interface(void);

#endif
