#pragma once

/****************************************************************************
 * Included Files
 ****************************************************************************/
#include "btm_manager.h"
/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/
typedef enum {
    AVRCP_PANEL_OPERATION_SELECT,
    AVRCP_PANEL_OPERATION_UP,
    AVRCP_PANEL_OPERATION_DOWN,
    AVRCP_PANEL_OPERATION_LEFT,
    AVRCP_PANEL_OPERATION_RIGHT,
    AVRCP_PANEL_OPERATION_RIGHT_UP,
    AVRCP_PANEL_OPERATION_RIGHT_DOWN,
    AVRCP_PANEL_OPERATION_LEFT_UP,
    AVRCP_PANEL_OPERATION_LEFT_DOWN,
    AVRCP_PANEL_OPERATION_ROOT_MENU,
    AVRCP_PANEL_OPERATION_SETUP_MENU,
    AVRCP_PANEL_OPERATION_CONTENTS_MENU,
    AVRCP_PANEL_OPERATION_FAVORITE_MENU,
    AVRCP_PANEL_OPERATION_EXIT,
    AVRCP_PANEL_OPERATION_0,
    AVRCP_PANEL_OPERATION_1,
    AVRCP_PANEL_OPERATION_2,
    AVRCP_PANEL_OPERATION_3,
    AVRCP_PANEL_OPERATION_4,
    AVRCP_PANEL_OPERATION_5,
    AVRCP_PANEL_OPERATION_6,
    AVRCP_PANEL_OPERATION_7,
    AVRCP_PANEL_OPERATION_8,
    AVRCP_PANEL_OPERATION_9,
    AVRCP_PANEL_OPERATION_DOT,
    AVRCP_PANEL_OPERATION_ENTER,
    AVRCP_PANEL_OPERATION_CLEAR,
    AVRCP_PANEL_OPERATION_CHANNEL_UP,
    AVRCP_PANEL_OPERATION_CHANNEL_DOWN,
    AVRCP_PANEL_OPERATION_PREVIOUS_CHANNEL,
    AVRCP_PANEL_OPERATION_SOUND_SELECT,
    AVRCP_PANEL_OPERATION_INPUT_SELECT,
    AVRCP_PANEL_OPERATION_DISPLAY_INFO,
    AVRCP_PANEL_OPERATION_HELP,
    AVRCP_PANEL_OPERATION_PAGE_UP,
    AVRCP_PANEL_OPERATION_PAGE_DOWN,
    AVRCP_PANEL_OPERATION_POWER,
    AVRCP_PANEL_OPERATION_VOLUME_UP,
    AVRCP_PANEL_OPERATION_VOLUME_DOWN,
    AVRCP_PANEL_OPERATION_MUTE,
    AVRCP_PANEL_OPERATION_PLAY,
    AVRCP_PANEL_OPERATION_STOP,
    AVRCP_PANEL_OPERATION_PAUSE,
    AVRCP_PANEL_OPERATION_RECORD,
    AVRCP_PANEL_OPERATION_REWIND,
    AVRCP_PANEL_OPERATION_FAST_FORWARD,
    AVRCP_PANEL_OPERATION_EJECT,
    AVRCP_PANEL_OPERATION_FORWARD,
    AVRCP_PANEL_OPERATION_BACKWARD,
    AVRCP_PANEL_OPERATION_ANGLE,
    AVRCP_PANEL_OPERATION_SUBPICTURE,
    AVRCP_PANEL_OPERATION_F1,
    AVRCP_PANEL_OPERATION_F2,
    AVRCP_PANEL_OPERATION_F3,
    AVRCP_PANEL_OPERATION_F4,
    AVRCP_PANEL_OPERATION_F5,
    AVRCP_PANEL_OPERATION_VENDOR_UNIQUE,
    AVRCP_PANEL_OPERATION_NEXT_GROUP,
    AVRCP_PANEL_OPERATION_PREV_GROUP,
    AVRCP_PANEL_OPERATION_RESERVED,
} AVRCP_PANEL_OPERATION;

typedef enum {
    AVRCP_PRESS,
    AVRCP_RELEASE,
    AVRCP_HOLD
} AVRCP_PANEL_STATE;
