/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef FEATURE_BLUETOOTH_CONSTANT_H_
#define FEATURE_BLUETOOTH_CONSTANT_H_
#include "feature_exports.h"

typedef enum {
    A2DP_SINK,
    A2DP_SOURCE,
    HFP_AG,
    HFP_HF,
    HID_DEVICE,
    PAN_USE,
    MAX_FEATURE_ID,
} feature_profile_t;

typedef enum {
    ON_ADAPTER_STATE_CHANGE,
    ON_DISCOVERY_RESULT,
    ON_BOND_STATE_CHANGE,
    A2DPSINK_ON_CONNECT_STATE_CHANGE,
} bluetooth_feature_callback_id_t;

typedef struct {
    void *feature;
    FtCallbackId callbackId;
} feature_callback_t;

typedef struct callback_info {
    bluetooth_feature_callback_id_t callback_id;
    FtCallbackId feature_callback_id;
    void *feature;
    void *data;
} callback_info_t;

void feature_bluetooth_deal_callback(int status, void *data);
char *StringToFtString(const char *str);
void feature_bluetooth_create_bt_ins();
void feature_bluetooth_destroy_bt_ins();
void feature_bluetooth_set_bt_ins(FeatureProtoHandle protoHandle);
void feature_bluetooth_clean_bt_ins(FeatureProtoHandle protoHandle);
bt_instance_t *feature_bluetooth_get_bt_ins(FeatureInstanceHandle feature);
#endif // FEATURE_BLUETOOTH_CONSTANT_H_