/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef FEATURE_BLUETOOTH_INS_MANAGE_H_
#define FEATURE_BLUETOOTH_INS_MANAGE_H_

#include <unordered_map>
#include "bluetooth.h"
#include "bt_adapter.h"
#include "feature_exports.h"


typedef std::unordered_map<void*, FtCallbackId> feature_callbacks_t;
typedef struct {
    feature_callbacks_t on_adapter_state_changed_cbs;
    feature_callbacks_t on_discovery_result_cbs;
    feature_callbacks_t on_bond_state_changed_cbs;
} adapter_feature_callbacks_t;

void bluetooth_init_ins();
void bluetooth_uninit_ins();
void clean_feature_adapter_callback(void* feature);
bt_instance_t* feature_bluetooth_get_instance();
adapter_feature_callbacks_t* get_adapter_cbs();
bool bt_feature_allocator(void **data, uint32_t size);
#endif // FEATURE_BLUETOOTH_INS_MANAGE_H_
