/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef FEATURE_BLUETOOTH_CONSTANT_H_
#define FEATURE_BLUETOOTH_CONSTANT_H_
#include "feature_exports.h"

typedef enum {
    A2DP_SINK,
    A2DP_SOURCE,
    HFP_AG,
    HFP_HF,
    HID_DEVICE,
    PAN_USE,
    MAX_FEATURE_ID
} feature_profile_t;

typedef struct {
    void* feature;
    FtCallbackId callbackId;
} feature_callback_t;
#endif // FEATURE_BLUETOOTH_CONSTANT_H_