/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef FEATURE_A2DPSNK_H_
#define FEATURE_A2DPSNK_H_

#include "feature_exports.h"
#include <unordered_map>

typedef std::unordered_map<void*, FtCallbackId> feature_callbacks_t;
typedef struct {
    feature_callbacks_t a2dp_sink_connection_state_cbs;
} a2dp_sink_feature_callbacks_t;

void a2dp_sink_feature_init(void* handle);
void a2dp_sink_feature_uninit(void* handle);
#endif // FEATURE_A2DPSNK_H_