/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
*/

 /*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

 /* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_H_
#define JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_bluetooth_onRegister(const char* feature_name);
void system_bluetooth_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_onUnregister(const char* feature_name);

// Struct defines
typedef struct _OpenAdapterParams {
  FtBool operateAdapter;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_bluetooth_OpenAdapterParams;

system_bluetooth_OpenAdapterParams* system_bluetoothMallocOpenAdapterParams(void);

typedef struct _CloseAdapterParams {
  FtBool operateAdapter;
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_bluetooth_CloseAdapterParams;

system_bluetooth_CloseAdapterParams* system_bluetoothMallocCloseAdapterParams(void);

typedef struct _GetAdapterSuccessResult {
  FtBool available;
  FtBool discovering;
} system_bluetooth_GetAdapterSuccessResult;

system_bluetooth_GetAdapterSuccessResult* system_bluetoothMallocGetAdapterSuccessResult(void);

typedef struct _GetAdapterStateParams {
  FtCallbackId success;
  FtCallbackId fail;
  FtCallbackId complete;
} system_bluetooth_GetAdapterStateParams;

system_bluetooth_GetAdapterStateParams* system_bluetoothMallocGetAdapterStateParams(void);

typedef struct _adapterStateCallbackData {
  FtBool available;
  FtBool discovering;
} system_bluetooth_adapterStateCallbackData;

system_bluetooth_adapterStateCallbackData* system_bluetoothMallocadapterStateCallbackData(void);


// Function wrappers to be implemented
void system_bluetooth_wrap_openAdapter(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_OpenAdapterParams * params);
void system_bluetooth_wrap_closeAdapter(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_CloseAdapterParams * params);
void system_bluetooth_wrap_getAdapterState(FeatureInstanceHandle feature, union AppendData append_data, system_bluetooth_GetAdapterStateParams * params);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented
FtCallbackId system_bluetooth_get_onadapterstatechange(void* feature, union AppendData append_data);
void system_bluetooth_set_onadapterstatechange(void* feature, union AppendData append_data, FtCallbackId onadapterstatechange);

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_H_
/* clang-format on */
