/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_A2DPSINK_H_
#define JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_A2DPSINK_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_bluetooth_bt_a2dpsink_onRegister(const char* feature_name);
void system_bluetooth_bt_a2dpsink_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_bt_a2dpsink_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_bt_a2dpsink_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_bt_a2dpsink_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_bt_a2dpsink_onUnregister(const char* feature_name);

// Struct defines
typedef struct _OnConnectStateChangeData {
  FtString _deviceId;
  FtInt _connectState;
} system_bluetooth_bt_a2dpsink_OnConnectStateChangeData;

system_bluetooth_bt_a2dpsink_OnConnectStateChangeData* system_bluetooth_bt_a2dpsinkMallocOnConnectStateChangeData();


// Function wrappers to be implemented

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented
FtCallbackId system_bluetooth_bt_a2dpsink_get_onconnectstatechange(void* feature, AppendData append_data);
void system_bluetooth_bt_a2dpsink_set_onconnectstatechange(void* feature, AppendData append_data, FtCallbackId onconnectstatechange);

// Array malloc functions

#endif // JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_A2DPSINK_H_
/* clang-format on */
