/*
 * This file is auto-generated by jsongensource.py, Do not modify it directly!
 */

/*
 * Copyright (C) 2023 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#ifndef JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_H_
#define JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_H_

#include "feature_exports.h"
#include "feature_log.h"

#include <ffi.h>
#include <assert.h>
#include <cstdarg>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_bluetooth_bt_onRegister(const char* feature_name);
void system_bluetooth_bt_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_bt_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_bt_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);
void system_bluetooth_bt_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);
void system_bluetooth_bt_onUnregister(const char* feature_name);

// Struct defines
typedef struct _StartDiscoveryParams {
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_StartDiscoveryParams;

system_bluetooth_bt_StartDiscoveryParams* system_bluetooth_btMallocStartDiscoveryParams();

typedef struct _StopDiscoveryParams {
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_StopDiscoveryParams;

system_bluetooth_bt_StopDiscoveryParams* system_bluetooth_btMallocStopDiscoveryParams();

typedef struct _DiscoveryResultCallbackData {
  FtString _deviceId;
  FtString _name;
  unsigned int _cod;
  unsigned int _rssi;
} system_bluetooth_bt_DiscoveryResultCallbackData;

system_bluetooth_bt_DiscoveryResultCallbackData* system_bluetooth_btMallocDiscoveryResultCallbackData();

typedef struct _ConnectProfilesParams {
  FtString _deviceId;
  FtArray* _profiles;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_ConnectProfilesParams;

system_bluetooth_bt_ConnectProfilesParams* system_bluetooth_btMallocConnectProfilesParams();

typedef struct _DisconnectProfilesParams {
  FtString _deviceId;
  FtArray* _profiles;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_DisconnectProfilesParams;

system_bluetooth_bt_DisconnectProfilesParams* system_bluetooth_btMallocDisconnectProfilesParams();

typedef struct _DisconnectParams {
  FtString _deviceId;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_DisconnectParams;

system_bluetooth_bt_DisconnectParams* system_bluetooth_btMallocDisconnectParams();

typedef struct _connectedDevice {
  FtString _deviceId;
  FtString _name;
  FtInt _cod;
} system_bluetooth_bt_connectedDevice;

system_bluetooth_bt_connectedDevice* system_bluetooth_btMallocconnectedDevice();

typedef struct _onBondStateChangeData {
  FtString _deviceId;
  FtInt _bondState;
} system_bluetooth_bt_onBondStateChangeData;

system_bluetooth_bt_onBondStateChangeData* system_bluetooth_btMalloconBondStateChangeData();

typedef struct _RemoveBondedParams {
  FtString _deviceId;
  FtCallbackId _success;
  FtCallbackId _fail;
  FtCallbackId _complete;
} system_bluetooth_bt_RemoveBondedParams;

system_bluetooth_bt_RemoveBondedParams* system_bluetooth_btMallocRemoveBondedParams();

typedef struct _GetDeviceNameParams {
  FtString _deviceId;
} system_bluetooth_bt_GetDeviceNameParams;

system_bluetooth_bt_GetDeviceNameParams* system_bluetooth_btMallocGetDeviceNameParams();

typedef struct _GetDeviceClassParams {
  FtString _deviceId;
} system_bluetooth_bt_GetDeviceClassParams;

system_bluetooth_bt_GetDeviceClassParams* system_bluetooth_btMallocGetDeviceClassParams();


// Function wrappers to be implemented
void system_bluetooth_bt_wrap_startDiscovery(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_StartDiscoveryParams * params);
void system_bluetooth_bt_wrap_stopDiscovery(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_StopDiscoveryParams * params);
void system_bluetooth_bt_wrap_connectProfiles(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_ConnectProfilesParams * params);
void system_bluetooth_bt_wrap_disconnectProfiles(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_DisconnectProfilesParams * params);
void system_bluetooth_bt_wrap_disconnect(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_DisconnectParams * params);
FtBool system_bluetooth_bt_wrap_getConnectState(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId);
FtArray* system_bluetooth_bt_wrap_getConnectedDevices(FeatureInstanceHandle feature, AppendData append_data);
FtArray* system_bluetooth_bt_wrap_getBondedDevices(FeatureInstanceHandle feature, AppendData append_data);
void system_bluetooth_bt_wrap_removeBondedDevice(FeatureInstanceHandle feature, AppendData append_data, system_bluetooth_bt_RemoveBondedParams * params);
FtBool system_bluetooth_bt_wrap_setScanMode(FeatureInstanceHandle feature, AppendData append_data, FtInt scanMode);
FtInt system_bluetooth_bt_wrap_getScanMode(FeatureInstanceHandle feature, AppendData append_data);
FtString system_bluetooth_bt_wrap_getDeviceName(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId);
unsigned int system_bluetooth_bt_wrap_getDeviceClass(FeatureInstanceHandle feature, AppendData append_data, FtString deviceId);

// Interface constructors

// interface vtable functions to be implemented

// Property getters and setters to be implemented
FtCallbackId system_bluetooth_bt_get_discoveryresult(void* feature, AppendData append_data);
void system_bluetooth_bt_set_discoveryresult(void* feature, AppendData append_data, FtCallbackId discoveryresult);
FtCallbackId system_bluetooth_bt_get_onbondstatechange(void* feature, AppendData append_data);
void system_bluetooth_bt_set_onbondstatechange(void* feature, AppendData append_data, FtCallbackId onbondstatechange);

// Array malloc functions
FtArray* system_bluetooth_bt_malloc_string_array();
FtArray* system_bluetooth_bt_malloc_int_array();

#endif // JSON_AST_GEN_MODULE_SYSTEM_BLUETOOTH_BT_H_
/* clang-format on */
